### ISSUE TITLE
DD Portal Forms: Enhanced Logic

### ISSUE THREAD

**Issue by FluidNets-DamianS** [DeskDirector/UserVoice#107]
The current forms is great.  However there is a severe limitation with loading a form after selecting the issue type.  I suggest a forms 2.0 where the data from the forms is used to select the issue/type/board/priority/etc data.  This way we could build robust Q/A forms that allow us to identify the way a user experiences a problem.

1.  I am having a problem with: (**computer**, server, phone, mobile device, internet)
2.  My computer: (will not power on, **has an error message**, is running slow)
3.  The error message is: (from Windows, **from another Application**)
4.  The application is: (Outlook, Word, Excel, **Adobe**, Google, etc...)
5.  I (am, **am not**) able to work around this issue.

Using the sample above we could raise the priority based on either Windows not powering on (2) or from the user not being able to work around the issue (5).  In addition as far as type/sub-type/ we know it is the following based on the answers.
Type:  Application
Sub-Type:  Adobe
Item:  Error

**Comment by Nness** [comment]
The logic you present there is great, from development point of view it's a bit complex to have UI to simply link multiple questions result to ticket setting.

One of setting I could think of is a rule set.
(1:2 means first question, second one been selected. 2:3|4 means second question's 3rd or 4th answer been selected. 3:1&3 means third question's 1st and 3rd answer been selected)

* When 2:1 priority is low
* When 1:3 and 3:2|5 and 4:1 priority is high
* When 6:2 type is xxx

System will go through all rules from top to bottom, then use final result setting. This is more user friendly one I can think of at moment.

The other system is either zapier or an javascript process in our system. 

JavaScript process in our system that means we will execute a given script for specific form when it is submit to create ticket.

The problem for this is the validation on JavaScript code, it might be good to simply rely on zapier, since zapier and flow has record. They are designed and implemented well. Re-invent wheel to achieve their quality that means a whole new product we need to cover.

**Comment by FluidNets-DamianS** [comment]
I like the idea of being able to keep it in house if at all possible.  However being able to link out to zapier is great if we need to calculate some advanced logic.

As some answers maybhave direct or indirect correlation to types or subtype.  Maybe I offer Word, Excel, Outlook, etc but the subtype is office although that may come to the zapier part.

Another thought would be to be able to do a simple scoring of questions where answers have different values and every x points we increase the urgency.

**Comment by FluidNets-DamianS** [comment]
Although I think I just realized that using zapier I may be able to do it today although it would be a lot of work and every ticket would need to be processed through zapier.

**Comment by FluidNets-DamianS** [comment]
However the real benefit is to have the ability to offer kb solutions to the user (other feature request)

**Comment by Nness** [comment]
For form logic, it can become very complex, when it is the case, we are trying to use UI to create a programmable language.

Where Zapier or Flow would be perfect suit for that. Since JavaScript or C# coding language can perform complex logic. The down side is the more form you have, the more work you have to perform.

Also on cost, Zapier is very expensive but easy to use. Flow and MSFT connector is cheap but harder to create compare to Zapier.

Currently, webhook included are following.
* Each form have it's own webhook. Restriction each form can only have 1 webhook
* Ticket created webhook will include form reference, where you can use reference to retrieve form result.

As we are planning to allow submit form as ticket note, we might want to add more options to webhook. For example allow form to accept more than 1 webhook config, introduce global webhook for all forms submission. (Submit form as ticket note is sneak peak of what we are planning, no ETA yet. )

For Zapier or Flow to process different form result, one of difficulty is unique ID for each field and answer, that is different for different form. Since ID is automatically generated on field or answer creation. You could using naming convention at moment, but introduce customer preferred token or tag for each question and answer might be another way of doing things. That way one zap or flow can manage all ticket or note creation.

**Comment by FluidNets-DamianS** [comment]
@Nness ,
Yeah, the Zapier costs I am worried about.  However I just realized that the only reason I am using them is because of the CW plugin.  I guess I dont need to use that as i can use DD api, right?  We wrote a python script that flatten all form data from DD so we can easily grab the data and do stuff with it.

What do you mean each form can only have 1 webhook?

**Comment by Lowell-Syncrety** [comment]
Would love to see examples of how to use DD webhooks with Flow, to affect ConnectWise Manage!

**Comment by FluidNets-DamianS** [comment]
Per my comment in #119 you need to build a connector that replaces the "script" function in Zapier, or use a connector.  I though DD was talking about doing this but not sure.  We have one that was written with the possibility of allowing other companies to use as well.

**Comment by Lowell-Syncrety** [comment]
Yeah, would love it if DD built a connector so we could use DD Forms -to - Flow - to - CWM.  They could totally charge it as an add-on.

Back in the Phil days there was a goal to build a workflow engine that was far more capable than CWM's hamstrung workflow engine.  That was so exciting to hear but haven't heard of it for years.  This would be a great (another) product to charge as an add-on that we'd love to use.  I haven't seen any other integrators build a workflow engine for CWM.

**Comment by Nness** [comment]
The decision to use Zapier and Microsoft Flow is we do not reinvent wheel. Microsoft spent tons of resources on their Flow, include Zapier too, they are very powerful. When things is powerful it is hard to use, when it is easy to use it won't be as powerful.

Msft Flow or Zapier, they all have history record, replay functionalities, with good documentations and very good code quality. Millions of customer rely on those products, which means the quality is guaranteed. 

If we make it, we can get few simple workflow done easy, but to achieve extreme complexity tasks, it always need some kind of code to run with it. Interface on workflow can only go so far.

**Comment by Lowell-Syncrety** [comment]
Oh, I think Flow is great and a smart way to go.  Just need DD to provide that sweet connector.  But it's possible that we might be able to figure out a way to build it ourselves.  I just don't like having to put out the time when someone else has already done it, and worse, my solution only works for me.  I prefer when a solution can be distributed (resold) so that it can be used for a ton of partners.  :)

**Comment by Nness** [comment]
With combination of dynamic field, ability to change field identifier, automation support. People can achieve what has been described here. We consider this as completed.
