### ISSUE TITLE
[10908] Disable "Something Else" option on New Portal UI

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#109]
Including the ability to disable the "Something Else" option on the New Support Request System under DD Labs.

In some use cases, making forms the only option provides a consistent experience and ensures required information is filled out by the clients

![image](https://user-images.githubusercontent.com/30588784/43166499-d02c6f84-8fea-11e8-9a65-92b41eacb8df.png)

![image](https://user-images.githubusercontent.com/30588784/43166444-ad8c17d6-8fea-11e8-8ce1-89d2ee90e356.png)

**Comment by Nness** [comment]
When end user constantly select `something else`, one thing service provider can perform is have a chat with them. Tell them that you want to resolve their issue faster, in which way you can help them on that? What's the problem they have on finding right form to submit ticket? Are there any difficulty when they trying to fill out form.

As request type is customize able, then service provider is also designer, service provider should take time to design and review the things they designed, not in a way when it is not functional and enforce end user to use it.

This is also true from our side too. Thus I didn't close this right away. So if there is compelling reason, I'm happy to revert this decision.

**Comment by FluidNets-DamianS** [comment]
@Nness , we allow email submissions too but my goal is to push users more and more to use the portal for support.  Especially with the ability to chat immediately with a tech is a compelling feature.  However I too have those users that will not fill out a form and opt for the "something else".  Simply the ability to disable this option would be sufficient.
By preventing "something else" we can ensure that tickets submitted via the portal have all the needed workflows, assignments, escalations, etc automatically occur.  Something else breaks all of that just like email.  However I plan to solve that by training my service desk staff to let email tickets sit for at least x hours before addressing.  ;)

**Comment by AirLHull** [comment]
Fully agree with Damien, we have clients that will choose this option because it will get their ticket logged quicker and unfortunately that is what people will do!

We have created Forms specifically for "My change is not listed" or "My Problem is not listed", having this "Something Else" also contradicts these forms i have created.   

The 2 above forms are also not the first forms the user see's, we aim to have them either as low down or near to the bottom as possible, if its harder to find for the client, there more likely to have a good look through the form subjects and choose one's that are more suited to the ticket they want to log.

I then actively monitor these tickets that were logged with the forms above, and create the form for the users.

We are heavily pushing ticket submission through DD over e-mail, and we have noticed at large increase of DD usage over the past year or so.

.... + Damiens comment

**Comment by Nness** [comment]
Cool. Thanks for explanation. If we list `something else` at bottom of the request types list, would that be the fix? Is it the case where `something else` is too obvious that they can click right away without go through request types list?

During design we actually talked about the options, whether put at bottom of list or put at side. At end we choose at side.

If we put at bottom of list, it will be similar as you guys create something your own. Of course the wording might not something you guys prefer.

Solution can be:
* We put `something else` at bottom of the request types list.
* Provide setting to disable `something else`, setting also state that when disable it, it is better to create one of your own to help user out.

**Comment by Andrew-Lahikainen** [comment]
I would be against redesigning this feature. I wouldn't so much be against a toggle for it. I just think that we aren't giving users enough credit. I believe that they will try to find the request type that they need 99% of the time and use the feature appropriately. It even tells them that they won't necessarily get a fast resolution if they use this button which you can't really do by defining your own request type as @AirLHull suggested.

Are you guys opposed to this feature because it might impact your service metrics? SLAs etc?

**Comment by Andrew-Lahikainen** [comment]
@FluidNets-DamianS do you ever run into the situation where the wrong workflows kick-off because someone used the wrong request type? I can see this happening in some cases, because there is no escape route. People will just choose anything.

**Comment by FluidNets-DamianS** [comment]
We are not 100% live with DD today (next week we go 100%).  We do have occasional wrong workflow in other scenarios sometimes.  I just need to make my orgs efficiency increase and I already have users bypassing forms using "something else".  In addition today out of 2000+ endpoints I only have about 20+ users that actually submit requests - so out of 20 I already have difficult users.  As we transition to DD & AISP MSP model we are asking all users to submit their issues directly as soon as they happen since there is no extra cost to the client.  If there is a wrong way - they will find it.

**Comment by Andrew-Lahikainen** [comment]
@FluidNets-DamianS thanks for the reply :)

I think we should:

* Add a Something Else permission
* Allow Something Else to be configured

If Something Else could be configured to have a certain source or priority, then these tickets could easily be delayed, which would allow tickets submitted via the Portal to be done first.

If we add a permission, I still think people really should try leaving Something Else enabled. We have done the same for our support Portal with FastTrack. Everyone has this permission and so far we have only had one instance of someone abusing it. We informed them of what issues we consider "FastTrackable" and they stopped. If they continued to abuse FastTrack, we would have disabled it for them for a period of time. I think this is a good example of a feature that would make MSPs nervous when thinking about it, but in practise it's fine. I've heard from one other Auckland MSP doing the same with similar results.

**Comment by prysmcorp** [comment]
I'm with @Andrew-Lahikainen on this. The main issue I saw with the Something else option is I could not configure with the proper ticket status in CW. Furthermore, I did not have control as to which service board it was landing on. So bare minimum having the ability the set some parameters on the Something Else option, kind of like you do on service requests, would be ideal.

**Comment by Nness** [comment]
@prysmcorp . Configure default board for `Something Else` is coming. It should be there within next few weeks.

The first option we introduce is board setting. And we might introduce other settings later on if needed.

**Comment by FluidNets-DamianS** [comment]
Here is another idea...   Along with the new options of "something else" I would be nice to:

1. Move that to the last option in ticket categories (based on new UI)
2. The area on the right currently used for "something else" to be configurable content:
    - Broadcast Info
    - HTML content
    - Plain old text box

I would personally use for HTML content and use it to show status information for different services we offer.

**Comment by Nness** [comment]
@FluidNets-DamianS  We actually considered that when we initially designed it. We will have discussion on this and keep everyone updated.

**Comment by bobsquid** [comment]
@Lowell-Syncrety I completely agree.  We have set processes in place, and forcing us to use this "something else" feature completely short circuits those processes.  

Our users were content using the forms before we moved to the new interface, and it really helped speed things along.  Now I find more and more users are just clicking "something else" because they are too lazy to fill out a form, and then they are complaining that things are taking longer because we have to contact them for more info.  It's just human nature.  Why should I have to train users to not press a button that is so readily available?  I already have a form for "other issues" which not only handles those tickets the way I need them handled, but also prompts me to review whether a new form should be created to address a new type of issue going forward.

Forcing this button on us is really making me consider reverting our clients back to the old interface.  The other new functionality is good, but it's not worth creating client dissatisfaction and slowing down our service.  

Just make it optional and let us run our businesses the way we want them run.

**Comment by Lowell-Syncrety** [comment]
Yep.  If business-process-altering features are to be introduced I'd like to see a voting/feedback option before they're deployed when we aren't given the choice.  DeskDirector should be facilitating our ability to implement our business processes, not disabling it.

**Comment by prysmcorp** [comment]
@Lowell-Syncrety Fully agree with your statements. This has been a primary reason we have not rolled out the new request support design.

**Comment by Andrew-Lahikainen** [comment]
This has been implemented. You can disable this globally here:

![image](https://user-images.githubusercontent.com/10571313/52016340-1f54c400-2549-11e9-8fdf-92d86e27b3bc.png)
