### ISSUE TITLE
DD Tech: Broadcast: Allow selection of CW Groups (members or companies)

### ISSUE THREAD

**Issue by FluidNets-DamianS** [DeskDirector/UserVoice#112]
As I was playing with the broadcast feature it appears that the ability to access the CW groups instead of choosing a company would be a needed feature.  This could be done one of two ways:

1) Choosing the group only selects the members of that group.  Although this would require the ability for broadcasts to be sent to specific users and not all users of a specific company.

2) Use Groups as a filter for the existing company selector.  I have a group called "VIT-Sync Customers".  It currently contains only the POC for each customer that uses our VIT-Sync service.  If I chose this group I do not expect to see individual users but any companies with any users linked to this CW group.  I can select specific or all companies that utilize this service and send them a broadcast about an issue with this service.

The 2nd option would be my preferred.

**Comment by FluidNets-DamianS** [comment]
Also, companies that are listed even in its current state should follow this filter from admin:
![image](https://user-images.githubusercontent.com/10325877/43403045-1ad52e36-93e2-11e8-81ab-b36440e44caa.png)

No reason to show companies that would NEVER be accessing the portal.

**Comment by Nness** [comment]
I'm sorry to say this, but I have to decline on this request. As 2016, we decide to move away from ConnectWise's setting, all setting and system should be stay inside DeskDirector.

Previous, any permissions, VIP, All tickets, Recommendation etc was defined use ConnectWise group, and we spent an year to migrate all setting to our own through 2016. This include dependency on ConnectWise group, ConnectWise request type etc.

The goal is if anything happen, we can point at our own system and say this is how it is configured and we can directly know what went wrong. Instead of digging through ConnectWise setting to try figure out what happened.

The other thing we try to avoid is to query ConnectWise as less as possible. Keep how we query them as simple as possible.

Way back in 2012~2015, DeskDirector have to query through 3~4 different source from ConnectWise, some of them been documented, some other not. Some been official API some other not. All the resource we have spent was to use ConnectWise setting, to keep what you get from ConnectWise portal is what you get in DeskDirector. Previous support diagnose is simple go to ConnectWise portal, if anything different, then report to developer. 

It is nice to be able to achieve that, but the cost on maintain such complicated system is very taxing. Then in 2016 we changed direction and move setting to our own and use cascading override system to achieve  what we have achieved with ConnectWise setting.

Group itself doesn't have that big issue, but to understand what group includes is very heavy. What we did before was to cache group definition in our system and allow fast execution at our side, but that means cache could be stale and cache process could be very heavy for some of customers.

The matrix we looking at is how long it requires us to get information about that group, is that in several sec or few milliseconds. This is such configuration that we want to be retrieve in few milliseconds. By moving away from ConnectWise setting, portal's login, view ticket etc have improved tons. We value performance heavily.
