### ISSUE TITLE
[11017] A way to pass additional information through form

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#119]
When creating ticket with dd-form, we would like to pass additional information to ticket. One of use case is task list that technician should go through.

**Comment by Nness** [comment]
## Aaron's original note:

With the information currently processed to a client's PSA from a form, the "Statement" field doesn't pass through the information listed under description. This functionality was previously resolved:

![image](https://user-images.githubusercontent.com/30588784/43562289-d3e5482c-966f-11e8-9597-09bd45073159.png)

The solution above is to have notes against forms that Techs will check over, tasks like "Create AD Object" on a new user signup form.

Another solution around this, would be an additional form section labelled "Internal Note"

![image](https://user-images.githubusercontent.com/30588784/43562399-69189868-9670-11e8-8562-a8ae4ea3cf46.png)

Or a flag against the "Statement" section that would enable this to convert into an internal note:

![image](https://user-images.githubusercontent.com/30588784/43562451-b2f02c58-9670-11e8-8700-9d40dbdefd5f.png)

**Comment by Nness** [comment]
The idea from Aaron got rejected because of pollution inside form fields. When field stand inside form it should have constant meaning.

The purpose of field is:
* Provide information to **client**
* Gathering information into one ticket note (either internal or public)

The key is single responsibility.

The better implementation would be provide an property of form. So it become form's behaviour.
![2018-08-02_16h42_44](https://user-images.githubusercontent.com/1712143/43562841-232cc6fa-9673-11e8-9751-87912e74b2c7.png)

This is actually related to #107, but this one is more simple logic, it is based on form itself, while #107 based on the answers.

Both can be achieved through webhook.

This is implemented in portal, and during refactor to have API specifically for form ticket creation, we purposed removed that.

It is our fault the added into our product without go through a proven process. As where we at now, we want to understand the underneath problem and find a better way to implement for many not for one. Also not carry out any debt.

**Comment by Nness** [comment]
If more people could provide following topic instead of implementation would help out.

* What is my use case
* What am I trying to achieve

**Comment by Lowell-Syncrety** [comment]
I keep hearing devs and DD sales people come back and say that we can do such and such with webhooks.  I believe you, but we REALLY need one or two concrete examples posted in the KB on how to do this.  I'm not talking the basics that Zapier does, like add a new contact or business from a webhook; we're using DD Forms, we already have that information.

Use case?  I have a field on almost every form where a user can specify a due date.  How can I push this due date into the ticket's due date field?  I supposedly can do this with a webhook but DD wants to charge consulting fees to do this.  Why not just provide a couple of documented examples in the KB and make your product that much more amazing?

**Comment by Lowell-Syncrety** [comment]
In other use cases maybe the user selects an application from a short drop-down of their common LOB apps.  Then we want that to populate the Type/Subtype in our PSA with the same information.

Or another one, for a more "complex" example that would fix a feature I used to be able to use in DD via WuFoo forms:  I have a form for users wanting to order software or hardware.  This used to create an Opportunity in CW Manage.  Now that doesn't work, so I had to create a Sales ticket board and have this form go into there, and create a workflow in CWM that creates an Activity to remind me to create an Opportunity from this ticket and once done, I have to close the Activity and then the ticket on the Sales board.  Lots of work as opposed to it just creating the Opportunity.

I have more use cases if you want, but you get the idea.

**Comment by FluidNets-DamianS** [comment]
Part of the problem is that you simply need to be or have an API wiz to do it.  Most of what you are asking for we have done using zapier.  However you cant use the CW/Zapier plugin as it is too limited.  You have to test commands in Postman then implement in Zaps.  The downside while Zapier is easier it gets expensive really fast.

We did a bunch of stuff in zapier:
- Tickets with order requests (we create a 2nd sales ticket at the moment)
- Auto CC (where customers always want to be CC'd on user tickets)
- Population of type/subtype

We have since migrated to Flow since it is cheaper but there is no "Script processor" in FLOW.  You actually need to write a connector app to process.  We have talked about allowing other companies to use our connector (as it only receives "x" data and spits it back to flow as "y" so you can then act on it).

I can share our Zapier script as we are not using it anymore.  It takes the weird XML from the form and flattens it out into something more usable.

**Comment by Lowell-Syncrety** [comment]
We have a tech who is a wiz, and we will be getting him to learn the CW API.  But yes, I guess the limiting factor now would be connecting Flow to CWM.  Is that what you mean?  As in, Flow needs to connect to the CWM API to action ticket changes and that part isn't built into Flow?

**Comment by FluidNets-DamianS** [comment]
Getting data into CW is easy (relatively) as it is just an HTTP POST.   Getting the data from the form with variables to submit intelligent data into CW is where you need a connector/application (or script processor from Zapier).

![image](https://user-images.githubusercontent.com/10325877/48587775-752eae00-e902-11e8-9b94-d75fc33cdcff.png)

**Comment by FluidNets-DamianS** [comment]
So we have a really smart guy who wrote the "Connector App" and I can then create my own webhooks, send the data to the connector and get back all the fields as variables that can be pushed into CW or do other things with.

**Comment by Lowell-Syncrety** [comment]
Yeah, that's awesome! Should sell that to DD.  :)  Can you affect things like purchase orders, sales orders, and activities as well?  So much lacking in CWM workflows that I've longed for an external "app" that can do more.

**Comment by Lowell-Syncrety** [comment]
Oh also (and maybe this is better for a phone conversation) do you have to purchase the paid version of Flow for the more advanced work?

**Comment by FluidNets-DamianS** [comment]
Yeah someone will need a bumped license to run the flows.   You can call me after 1pm PST tomorrow to talk further.  805-856-1815

**Comment by Lowell-Syncrety** [comment]
Someone needs to build a process for utilizing webhooks in DD Forms, through Flow, to CWM. I wish I had time to learn this; it doesn't seem like rocket science, yet it feels like so few partners can really take advantage of webhooks without better guidance.

**Comment by Lowell-Syncrety** [comment]
I see a KB article "Webhook Example with Zapier" (https://help.deskdirector.com/article/a2os4eo8rh-webhook-example-with-zapier) which is great! I'd love a KB about using the ConnectWise Manage API and Flow. Don't have to detail how to get set up for API access, etc. (just a link to where someone would start out that process) but an example of pushing a DD form field to a ticket field would be great.

**Comment by Aycorn** [comment]
The original requirement around Task Lists is available as a feature now: [Task Lists](https://help.deskdirector.com/article/1u1ykcyqrb-introduction-to-task-lists)

Any bespoke requirements to push information to certain fields within a PSA can be achieved using a combination of [Events](https://help.deskdirector.com/article/bo8gdgjs5k-workflows) and [Power Automate](https://help.deskdirector.com/article/u8uqhpn5rs-get-started-with-the-desk-director-power-automate-connector).

Marking as closed.
