### ISSUE TITLE
DD Portal: Call Me Back

### ISSUE THREAD

**Issue by FluidNets-DamianS** [DeskDirector/UserVoice#120]
I had a conversation with a client who made a compelling point.  They a have 300+ end-users and he does not want them to use the call me back feature nor the ticketless chat feature and wants them removed from his account:

Call Back - There could easily be a misinterpretation of an expected SLA since the client requested a call and has notified us.  However since there is no ticket there would be no escalation or CW workflow for weekends or after hours.  In addition the client POC gets copies of all tickets so he can intervene as needed/ when needed.  He would not be able to do this with call backs.

Chat - the same goes for chat as end-users would have access to technicians without him being able to see what the users are requesting.

For us our goal would be to turn on the new support system for all, and disable on specific clients as requested.

**Comment by FluidNets-DamianS** [comment]
I am aware of these settings and i see that I can now enable the new system per company.  However I want all companies to use the latest setting and omit for this one currently so i have to update a dozen configs.  However the client made a valid point about callbacks.  I should be an option to convert to a ticket as we could then notify the user that this is outside the SLA, etc.  I did not see an API for the callback either.

**Comment by Nness** [comment]
Under `/admin/beta`. 

* Enable New Request Support System, this will enable new system for all companies
* Enable callback option in new request support system. You can use this to disable callback option inside request support selection panel. 
* Enable Pre-Ticket chat in new request support system. This will disable pre-ticket chat.

For your scenario. You can tick first one, disable second and third. There is no company level disable callback or pre-ticket chat at moment. The company level enable new support system is purely designed for testing. Once test is done, use first option to turn on globally.

![2018-08-08_09h51_04](https://user-images.githubusercontent.com/1712143/43804562-9345610a-9af0-11e8-9754-b8e52b5450c9.png)

**Comment by chris-ls** [comment]
Here is a possible implementation of the "call me back" and "pre ticket chat" features:

### Always create a ticket with a pre-ticket chat
When a user tries to initiate a chat from the Request Support page, we will ask them for a one-line description of their issue. We will then immediately create a ticket for this as well as launch a chat request.
There would be no need to create a ticket on the tech side and the ticket would automatically be created under the correct user/company. This ticket would be created on the default board with default settings.

### Remove "Call me back" as a primary support option on the "Request Support" page.
The call-back feature should only be used as an "escape route" or alternative option once the user has tried to get immediate support via chat, but wasn't successful.
There doesn't seem to be a strong use case to having it here as a first class support option.

### Requesting a call-back from within a chat session will add a ticket note.
Asking for a call-back still makes sense from the context of a new chat session, where no technician was available to answer.
Since there is now _always_ a ticket associated with a chat session (because we create a ticket even with pre-ticket chat), requesting a call-back will add a ticket note to the ticket.
The status of the session will still change to "callback" so a list of call-backs are visible inside DDTech.

### The callback toggle would now hide/show the call-back option displayed inside an unanswered chat session
Currently it only hides/shows the call-back support option on the Request Support page.
It would now hide/show the call-back escape route in an unanswered chat-session.

--

Doing it this way would mean there is **always** a ticket for a call-back/chat.
This simplifies a few things as we don't have to worry about different handling for call-back/chat with/without tickets.
This would solve the issue where there is a POC who reviews all support requests, as all action would be visible via tickets.

When requesting a call-back, do you think it is sufficient to simply add a ticket note?
The associated chat session would change its status to "callback" and would be visible inside DDTech.
We also have web-hooks for chat sessions, although that does require more work from the MSP to set up automation from that.

This would also resolve https://github.com/DeskDirector/UserVoice/issues/69

@FluidNets-DamianS Do you think the client would still object to the call-back and pre-ticket chat features if they were implemented in this way?

Thoughts?

**Comment by FluidNets-DamianS** [comment]
I like this idea 100%!  The only part I did not quire follow was:
> There would be no need to create a ticket on the tech side 

With chat being accessible via the API do you think it is possible for an MSP to develop just a chat App that can fully function via the API?

For us, we signed up for DDp over a year ago but it was just not something we could implement.  As of today we are now using DDp 100%.  I am excited about chat and the other features but I have been doing "tech duty" for the past week and found that DDtech would not suffice with our work flow.  I originally heard of "Tech" as referred to as a CW lite, however not one of our techs could just function in Tech as they would go back and forth to CW which is pointless.

Where DDtech is a perfect fit is where we have opened our CW to customer onsite IT.  It is more suited for their us and we have about 3 accounts and 8-10 techs that would use it.  However then i dont get "chat" and they get to "broadcast" to all clients since there is no security on broadcast setting.

**Comment by chris-ls** [comment]
> There would be no need to create a ticket on the tech side
The current pre-ticket chat flow is this:
1) User starts a pre-ticket chat
2) A tech handles it
3) They chat
4) The tech can *optionally* create a ticket and attach the chat session to it.

Part 4) is where there are issues.
Portal would take over this responsibility and _always_ create a ticket before even starting a chat.
So when a tech handles a pre-ticket chat inside DDTech, there is actually already a ticket created for it.

> With chat being accessible via the API do you think it is possible for an MSP to develop just a chat App that can fully function via the API?

Yep. Although the API isn't "officially" a public API, it is relatively stable. There also isn't any documentation for it right now.

> Where DDtech is a perfect fit is where we have opened our CW to customer onsite IT

This is getting somewhat off-topic from this thread, but it would be cool to have this elaborated on :)
I am trying to establish the various users/personas in your business model.
Is the "onsite IT" the same as the "POC" mentioned at the beginning of this thread?
What are their roles/duties?
Apart from making DDTech more suitable for different types of users, there is also the possibility of extending DDPortal. In some cases that might make more sense.

**Comment by FluidNets-DamianS** [comment]
I see the pre-ticket chat is creating tickets.  However the ticket number is not being populated in the API

```
  "chatid": "1536714761-3B43",
  "chatname": "I need help with something.",
  "createdDateTime": "2018-09-12T01:12:41.2496424Z",
  "chattype": "request",
  "ticketreference": "",
  "requestor": "Nanette Yoshimi",
  "requestorid": 2381,
  "company": "Lee & Associates - LA North",
  "companyid": 1345
```

**Comment by Nness** [comment]
Is this webhook result?

**Comment by FluidNets-DamianS** [comment]
yes

**Comment by chris-ls** [comment]
Hey Damian,

Created an issue [here](https://github.com/DeskDirector/Issues/issues/46) to address this.

**Comment by chris-ls** [comment]
Closing this ticket as I believe everything mentioned has been resolved some time ago!
