### ISSUE TITLE
[11032, 12923, 13675] Able to filter tickets by contacts

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#124]
Having the Contact Name indexed for searching within DD Portal.

This is primarily for contacts with "All Ticket" permissions, as larger companies can't easily locate tickets for specific users.

If it reduces stress on having this indexed for every user, enabling this functionality for All Ticket users would be a sufficient workaround.

**Comment by Nness** [comment]
Try to focus on the end result not implementation. :)

If directly ask index it. answer is no. We cannot perform that. It is not possible.

More detail:
* It is possible for ConnectWise's data
* It is currently not possible for Autotask.

What has been indexed? Contact id. Not contact name. Contact name won't be full text searchable.

What you have been asking is full text analyze to include contact name, since it is inconsistent behaviour. We could do for ConnectWise only, it is not preferred. 

This is more towards if we have mechanism to allow easily browse ticket base on contacts. Currently API is supporting that.

When we redesign ticket list on portal, we can take this into account.

**Comment by Aycorn** [comment]
_This is more towards if we have mechanism to allow easily browse ticket base on contacts. Currently API is supporting that._

This sounds like a better solution to the suggestion, if this could be taken into consideration would be great 👍

**Comment by Aycorn** [comment]
Similar request raised: Service Ticket #12923 - Searching old tickets

**Comment by Aycorn** [comment]
Similar request: Service Ticket #13675 - When trying to search by contact name, not all tickets are returned

**Comment by Andrew-Lahikainen** [comment]
Just an update - this is currently available in the new tickets UI. You can check it out by enabling it inside the feature preview section in the admin console.

**Comment by Andrew-Lahikainen** [comment]
Shipped
