### ISSUE TITLE
[11106] Additional Access for Invoices.

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#127]
Scenario: One customer currently has additional access to multiple companies, this shows tickets across these companies however doesn't grant permissions to Invoices.

The end goal would be for a client to access multiple companies invoices from one portal account.

**Comment by Nness** [comment]
For this request. we won't change anything on existing implementation, we do have plan to introduce new implementation for access to multiple companies.

Current issue on contact that can access multiple companies
* Contact cannot create ticket at given company
* Contact add note to ticket not belong to his company will result in wrong user name. System will use ticket's contact instead of current login contact to add note.

New implementation:
* Single contact can only access to single company. The company he belong to
* Contact can switch to other contact if email is same.
* Contact able to select one of contact to be default one. Thus, if there are 5 contacts with same email, it will have consistent experience on login.

In new implementation, it resolved previous issue also automatically resolved invoice and quotes issue. In that way given email have associate contact under different company.

Once new implementation is done, we could also add dashboard for those people, so they can get rough information on multiple contacts.

**Comment by Andrew-Lahikainen** [comment]
This is now possible with account switching
