### ISSUE TITLE
[11951, 14340] Change wording on "Request Support"

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#171]
Enable the ability to change the wording of the "Request Support" button:
![image](https://user-images.githubusercontent.com/30588784/46589524-ef4f6400-cb06-11e8-99d5-940f5bdf554a.png)

**Comment by Nness** [comment]
Need more information before it will be considered. What is the reason behind? What kind of problem you are facing?

**Comment by Lowell-Syncrety** [comment]
Not sure if this is the reason in OP but I have a form for folks who want to order something, so that goes to Sales; it's not a support request.  The previous "Create a ticket" was a bit more generic.  We also have forms for things like equipment moves that don't require our support, just an update in our documentation.

**Comment by Andrew-Lahikainen** [comment]
This can be done with the new menu system, closing.
