### ISSUE TITLE
Display or popup based on X-Frame-Options

### ISSUE THREAD

**Issue by PreciseNZ** [DeskDirector/UserVoice#177]
Some sites are now employing X-Frame-Options to stop other sites embedding their content.  In the Learning Centre, are we able to detect this, and then perhaps prompt the user to click the Pop-Out button, or even just pop the page out automatically rather than displaying a blank page?

**Comment by Nness** [comment]
I believe this has been implemented. @chris-ls could you confirm and close this?

**Comment by chris-ls** [comment]
Correct.

Any learning item which has been set to "Popup" inside the Admin Console will be unaffected and behave as normal. List items representing these will directly open a new tab/window.

Any learning item which hasn't been set to "Popup" will now perform a HEAD request when viewing.
If it is not embeddable due to X-Frame headers, a fallback "friendly message" will be displayed, instructing them to open in a new window.

![image](https://user-images.githubusercontent.com/5317900/50786345-2c9adc00-1318-11e9-9710-486696ad15f0.png)
