### ISSUE TITLE
[12052,15437, 19013, 20407] Granular Client/Customer groups.

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#182]
I would like the ability to group contacts at a client into "authorized levels" that can be tied into Request Type Filters and Permissions.

For example, CLIENT A has 5 contacts that are authorized to make employee changes/purchases so I only want those 5 contacts at that company to see the request type. These contacts would be "tagged" with a "User Change" template - this would then apply the appropriate permission across filters/permissions.

This will help make changes for new/leaving users easier across the portal - as the only option is to manually add users/companies on custom filters.

------

The decision on enhance the system been explained at [note here](https://github.com/DeskDirector/UserVoice/issues/182#issuecomment-513955063)

**Comment by PreciseNZ** [comment]
Additional related request:
I need the ability to be able to grant internal users access to the DDADMIN portal but specify which tabs they can access. Ideally I would like to specify each option under each tab however for now I need to be able to assign users to "Search" or "Portal" or System".

This is due to the business expanding internally and we are getting a large amount of utilization from Service Hub that I cannot administrate all the basic requests, and for security reasons I cannot provide every "Master admin" access to the portal.

**Comment by Aycorn** [comment]
Similar Request: Service Ticket #15437 - Users - Connectwise User Access Levels for filtering in DD

**Comment by ExR90** [comment]
I too would like this, specifically the usage of the Connectwise User Access Levels to set client/contact permissions inside DD.

**Comment by FluidNets-DamianS** [comment]
I concur.  Currently we have a MS Flow process that checks CW and update permissions.  Specifically the Primary contact gets access to all tickets and invoices.  The Billing contact gets access to invoices.

Damian C. Stalls<https://outlook.office365.com/owa/calendar/DamianStalls@fluidnets.onmicrosoft.com/bookings/>
vCIO Director<https://outlook.office365.com/owa/calendar/DamianStalls@fluidnets.onmicrosoft.com/bookings/>
805.856.1815 Direct<https://outlook.office365.com/owa/calendar/DamianStalls@fluidnets.onmicrosoft.com/bookings/>

**Comment by Nness** [comment]
With new admin console, we will introduce bulk action. The example will be following.

In new admin console, we support tags for company and contacts. That means you can tag several companies as "alpha". Then at one stage, you want to apply permissions to those alpha companies. You can simple go to an bulk modify page. Which will have following procedure.

* As for what tags you would like to use
* Search for all companies that have those tags and give an estimate count with sample list of 20 of them.
* Select an action. (Modify boards access, modify permissions etc)
* Create an template. (Such as list of boards)
* Click on apply, then system will go through all the companies to apply such configuration.

It will also allow bulk remove permissions, to allow top level inherit.

Group permission won't be implemented, since it conflict with existing cascading inherit system. Combine multiple permission system will cause confusion and hard to understand and use.

Each permission system have its own strength and down side. They all need different tooling to enhance and resolve issues. Thus DeskDirector will be focus on tooling instead of mix different concept.

**Comment by Aycorn** [comment]
@Nness is this live? And do we have a supporting KB article?

**Comment by Andrew-Lahikainen** [comment]
@Aycorn this hasn't been implemented yet

**Comment by Nness** [comment]
Request type collection has been designed to resolve this issue. #538  And it is under construction.
