### ISSUE TITLE
[12672, 13549, 14426, 19372, 20532] Sort options within DD Portal

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#196]
When someone who has full ticket view to all open tickets in an organization, it could be difficult to browse tickets if search is not used.

Would be ideal if there's a way to "sort" tickets by logged date, last update date, ticket age, Ticket logger name, etc

**Comment by bur4an** [comment]
[13549] Need more advanced search option to search for date rate, ticket contact, status, etc

**Comment by dr3dgen** [comment]
Any updates on this one? I think I see a few similar requests. Absolutely love the interface, but I have to admit that sorting through tickets to find specific ones can be challenging. The most common options we're missing from ConnectWise are sort by priority and by ticket contact. I think having those two would make a significant difference in time saved.

**Comment by awiedeman** [comment]
Also by statuses! Sort options would be huge!

business case: Clients might want to sort to those tickets where we are waiting on them ONLY.

**Comment by Andrew-Lahikainen** [comment]
@awiedeman I think we'd rather do status *filters* rather than sorting. Similar to DD Tech.

**Comment by awiedeman** [comment]
Tomato, potato. As long as it achieves the clients needs in slicing/dicing
the way they see their tickets.



BTW – not everyone uses DD Tech





*Ashley Wiedeman*

Director of Platform



Accessium Group Inc.

305 Spindrift Drive, Suite 2
Williamsville, NY 14221



716.828.8262: Direct

716.828.8324: Helpdesk Team



*CONFIDENTIALITY NOTICE:*


*This e-mail transmission may contain confidential or legally privileged
information that is intended only for the individual or entity named in the
e-mail address. If you are not the intended recipient, you are hereby
notified that any disclosure, copying, distribution, continued possession
or reliance upon the contents of this e-mail is strictly prohibited. If you
have received this e-mail transmission in error, please reply to the sender
so that Accessium Group Inc can arrange for proper delivery, and then
delete the message from your inbox. Thank You.*



*From:* Andrew Lahikainen <notifications@github.com>
*Sent:* Monday, October 21, 2019 4:01 PM
*To:* DeskDirector/UserVoice <UserVoice@noreply.github.com>
*Cc:* awiedeman <awiedeman@accessiumgroup.com>; Mention <
mention@noreply.github.com>
*Subject:* Re: [DeskDirector/UserVoice] [12672, 13549, 14426, 19372, 20532]
Sort options within DD Portal (#196)



@awiedeman <https://github.com/awiedeman> I think we'd rather do status
*filters* rather than sorting. Similar to DD Tech.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/DeskDirector/UserVoice/issues/196?email_source=notifications&email_token=ANH4LSLTENUG6MIB5K57S7DQPYDBJA5CNFSM4GD4HT5KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEB3TG7I#issuecomment-544682877>,
or unsubscribe

**Comment by Andrew-Lahikainen** [comment]
@awiedeman just an example of something you can take a look at and give your thoughts on the ux.

**Comment by awiedeman** [comment]
Hi - any sort of update on this?

**Comment by Andrew-Lahikainen** [comment]
shipped

**Comment by Andrew-Lahikainen** [comment]
![image](https://user-images.githubusercontent.com/10571313/73505561-b80d7080-4437-11ea-8cc5-f439cf23960b.png)
