### ISSUE TITLE
Forms - Add email notification

### ISSUE THREAD

**Issue by Lowell-Syncrety** [DeskDirector/UserVoice#198]
I just moved all our forms over from WuFoo and one feature I will miss is the capability to have a form emailed to me in some cases.  Like maybe a high priority request, or a sales order request... In one form I used to use that to request a quote from a vendor for a warranty extension.  The form would email 3 people at that vendor who needed the quote request and CC myself.

So it wasn't a form that my customers saw, or went into our PSA but I used as a quote request that made sure we got all the right information to the right people each time.

**Comment by Lowell-Syncrety** [comment]
Another use case is where we might use DD Forms for our customers, internally for things like vacation requests.  They fill out the form, the details get sent to their HR person internally via email.

**Comment by ronmutt77** [comment]
Yes this is badly needed.  I have the same needs.  Another example, would be if on a new employee setup form, one of the choices is to setup an account to an application that we don't directly support.  Like something the customer's internal IT, HR, 3rd party vendor or sales department supports.  When that choice is chosen in the form, the form emails that contact or other helpdesk system, so the request for that choice gets put in.

**Comment by ronmutt77** [comment]
We want our customers to rely on us and depend on the forms in Desk Director.  So we want a one stop for all of their forms, not just IT related.  And still, many tasks require both IT resources, and other non-IT resources to fully accomplish.

**Comment by Nness** [comment]
Recently we released our own email system for ticket life cycle. I can propose few ways of work around the issue to achieve similar capability. Also the possibility of alter existing email system to achieve more.

---
### Existing system:
Currently, DeskDirector's ticket life cycle include assigned member, ticket owner and CC. If there is automation that can add those additional users to the ticket as CC. Then, CC receive email event can achieve that.

---
### Future possibility 1
Currently, we also have status changed email event. If we can add additional receiver, that means when ticket changed to that status, status changed email event will trigger, email will send out to those additional receiver. 

---
### Future possibility 2
Extend email capability to also trigger by forms. That will be new type of email event. Depends on time needed, since admin page will need new section specific for that scenario. 

@Lowell-Syncrety  @ronmutt77 
For first solution, you can do it now. First second solution it is possibility also low development cost. Third solution will require design and longer development time, compare to second choice.

As for second choice, at current stage, it seems can resolve part of problem, but if not get used much, it will be a debt for us to support for long period of time.

Third option is exactly match with what you guys requested. I will have to take time and think about option 2 and option 3.
* Option 2: What kind of potential debt we will be facing and would that be a common scenario to be used.
* Option 3: What kind of design is suitable. One email template per form or one email template for multiple form. What is best and most used way. 

For DeskDirector, we are opinionated product. We don't want to achieve every single scenario, since that will require a lot of settings. More setting the worse it gets. Only have enough feature for common scenario is the goal.

Let me know what you guys think about option 1, 2, 3. So, I can put into my consideration.

**Comment by ronmutt77** [comment]
Silverlancer - Thanks for your email.  Are you a developer or product manager at Desk Director?

I am not sure I understand your options totally, but option 3 (Future possibility 2) is I think what I am looking for.  But, let me give another example, to clarify.

I would like to have the form trigger an email based on a choice that someone picks in the form (from a choice question).  The form option could simply be “send email based on this condition”, “or if this choice is picked” and define the choice answer, then enter email address to send form to.
WuFoo forms can do this.

Say I have a New Employee Setup Form.  On this for I have choice questions for all the items the new user needs.  Some of these items are HR related.  Or some may be to a 3rd party vendor, or to our customer’s internal IT department.  When that choice is picked, an email is sent to the resource that needs to know this choice was picked (In addition to the ticket being created as normal in our PSA).  And if that choice is not picked, then they do not get notified via email.

I hope I explained that clearly?



Ron Muttillo
Itek Systems, Inc.
"Making Your Net WORK !"
800-327-ITEK (4835)
440-510-8611
ron@itek-systems.com<mailto:ron@itek-systems.com>
www.itek-systems.com<http://www.itek-systems.com/>

**Comment by Nness** [comment]
I do understand your request, the thing is as I said it take time to develop. Where the resource is limited, what we can do is unlimited. What is priority, what can solve issues that majority of customer need is what I need to planning. 

Here is knowledge base article for latest email feature we have released. [You can take look](https://help.deskdirector.com/article/3s17fhf66a-setup-email-notifications-for-ticket-updates).

Once you understand current email system capability they you should know what I have written up there. 

If an alternative way that cost less to build and maintain, which we can sneak in between few other things we have already planned. Then it can cover more scenarios.

If sticking with one optimal way of solution, resource is limited, then time to wait could be lengthy.

**Comment by DDAndyChen** [comment]
@Lowell-Syncrety 

It is possible to do it via Microsoft Flow (aka Power Automate) with DD Flow Connector
Here is an [example](https://help.deskdirector.com/article/9q62ocuk3s-flow-integration-example-get-notified-on-a-form-entry).

**Comment by Nness** [comment]
You can do this with DD Flow connector or new Workflow system. We consider this as completed.
