### ISSUE TITLE
[13890, 13974, 15422, 20227] DD Portal: Microsoft OAuth for Native APP

### ISSUE THREAD

**Issue by Lowell-Syncrety** [DeskDirector/UserVoice#199]
Most of our customers use the DD Portal app and we have SSO configured via AD, and that works great.  Who wants to remember yet another password?  But some newer customers are smaller and don't have AD so they always have to use the token.  I'm guessing Microsoft OAuth via the app is hard to do, and why it's not there (if it's easy I'd love to see that option).

But could you have a link to the web portal that we could customize, so that it appears on the main logon page of the Portal app for these users?  Then they could have an alternate way of getting to the portal and use MS OAuth too.

**Comment by Nness** [comment]
We have started working on Microsoft OAuth for native app. Back-end is done, front end depends on schedule.

**Comment by Lowell-Syncrety** [comment]
@Nness Thanks for the update!

**Comment by Lowell-Syncrety** [comment]
Oops, didn't mean to close it.

**Comment by Aycorn** [comment]
Similar Request: Service Ticket #13890 - OAuth via DD desktop app

**Comment by Aycorn** [comment]
Similar Request: Service Ticket #13974 - OAuth not working

**Comment by palecekconsulting** [comment]
There doesn't seem to have been any movement since Nov '18? Can we get an update? This is preventing us from deploying the native app to many of our clients.

**Comment by chris-ls** [comment]
This is scheduled in for the current development cycle, which has just begun.
I would expect this to be available to you some time within the next month.

Will keep this updated.

**Comment by Lowell-Syncrety** [comment]
Thanks for the update!

**Comment by Lowell-Syncrety** [comment]
Any news on this? I just watched a video in the DD portal (https://support.deskdirector.com/portal/v2/content/menu/822185cd-6f49-4e25-b532-395f499097be/section/default/page/8fb7575f-52fb-4a0e-a741-d65f21377fd4) that says this is available on both the web version and the "installed version".

**Comment by Aycorn** [comment]
Similar request: Service Ticket #15422 - DDPortal / Desktop Installer Questions

**Comment by chris-ls** [comment]
Thanks for your patience guys.
We have recently released what is basically a rewrite of the Desktop application, from Javascript to Typescript.
The codebase needed some major work and it was getting difficult to add new features.

Now that this is done, this feature will be coming shortly.
It is planned to be completed in the upcoming weeks of work.

**Comment by Lowell-Syncrety** [comment]
Nice! Thanks for the update.

**Comment by chris-ls** [comment]
Just another update here:
This feature is delayed until the release of the V3 Desktop Client.
This is expected to be fully released/available in your Admin Console in ~1 month.

The V3 Desktop Client is targeted towards deprecating the current auto-updating installers. (V1 & V2)
The Microsoft OAuth functionality in V3 basically fell out for free due to the architectural changes but requires non-negligible work to get working in V2.

Since earlier Desktop Client versions are soon to be deprecated, this functionality will only be available with the new V3 client.

**Comment by Andrew-Lahikainen** [comment]
This has been shipped to Australia and New Zealand. All looks well. US and Europe to follow next week.

**Comment by Lowell-Syncrety** [comment]
> Just another update here:
> This feature is delayed until the release of the V3 Desktop Client.
> This is expected to be fully released/available in your Admin Console in ~1 month.
> 
> The V3 Desktop Client is targeted towards deprecating the current auto-updating installers. (V1 & V2)
> Since earlier Desktop Client versions are soon to be deprecated, this functionality will only be available with the new V3 client.

Will the V3 client also be auto-updating including the upgrade from V2 to V3 client?

**Comment by Andrew-Lahikainen** [comment]
@Lowell-Syncrety the V3 client will not auto-update. However, it now embeds the web version directly instead of distributing it along with the installer. This means that it will remain up to date with the web version which typically has a much faster release cycle. This also means that the logo and theme will be fetched at run time, rather than build time.

This means that the only time you need to manually update the software is when:
* You change your app's hotkey combination
* You change your app's desktop icon
* You change your app's name
* We release an update to the desktop code (very infrequent)

Overall this will be much better because it simplifies everything. Installing is simpler, development is simpler.

Your existing v2 clients *will* automatically update to v3, but after that they will not receive updates.

We will be sending an email to US/EU customers to let them know what's changed in a bit more detail, but I'm happy to answer and additional questions you have.

**Comment by Lowell-Syncrety** [comment]
Thanks for the update. So the existing SSO (with AD) functionality will also be present, and if the user is not found or it's not set up (i.e. users without local AD) they can use O365? This is going to be cool because there have been some times where a user's AD auth didn't work for some reason and they'll have the option to do O365.

**Comment by Andrew-Lahikainen** [comment]
@Lowell-Syncrety yep that's right, we will always try AD first.

**Comment by Andrew-Lahikainen** [comment]
This has been shipped to US/EU
