### ISSUE TITLE
[10233] Show more information in ticket tabs

### ISSUE THREAD

**Issue by Andrew-Lahikainen** [DeskDirector/UserVoice#2]
For ticket tabs, add the contact name to the tab to help identify which ticket you're after.

This is useful in the case where you're dealing with multiple tickets with the same summary, but for different people.

**Comment by Nness** [comment]
My suggestion might be huge change, but I will leave the idea here for discuss. Currently we have concept of tabs on top, what if tabs is on left side, which is more like email's list. Similar as HUD. This way we can display more information and we can have more items on there.

Of course this change will require huge layout change.

**Comment by Aycorn** [comment]
Closing:

* Web Portal DD Tech Tab Name includes Ticket Number and Time Summary
* Installed DD Tech client is now available and includes vertical tabs as mentioned in the comments
* Large UI overhauls to Tech since this was raised in 2018. Further feedback can be logged as new ideas with visual references
