### ISSUE TITLE
[12661, 19029] Pre-selected DD Form sections.

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#202]
Ability to have DD Form choices pre-selected:

![image](https://user-images.githubusercontent.com/30588784/48594671-60abed80-e9b6-11e8-927c-853a91f532be.png)

This will remain the default answer for a client unless they specify otherwise.

**Comment by Lowell-Syncrety** [comment]
This is handy; a "default" selection as an option on a question.  Don't always want a default but "choice with default" could be an option.

**Comment by chadgross** [comment]
This is by far the biggest thing we miss from Wufoo forms - and our users too.  We've gotten several complaints about new DD Forms taking longer to complete compared to the old Wufoo forms since users have to answer every question instead of providing a few key details and then just overriding any pre-selected default choices they may want to change.

**Comment by Nness** [comment]
This has been implemented and released.
