### ISSUE TITLE
[12660] Customer filtering not applying for Company Config filtering.

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#204]
The ability to apply the "Company Type Filter" and "Company Status Filter" filter to your admin page is available.

![image](https://user-images.githubusercontent.com/30588784/48746443-3e76e000-ecd4-11e8-8e07-33ae458aa82c.png)

The companies marked for this filtering aren't used when displaying contacts.

Feature request and/or bug raised to have customers falling under these categories not display from the Admin Console.

Example:
Company A has the type "Customer" and Status "Active"
Company B has the type "Former Customer" and statues "Inactive"

With the filter applied to show Customer A - contacts from Customer B will still display under "Maintain Contacts"

**Comment by Nness** [comment]
This is not bug, there is some technical reason that there is no join index between Company and Contacts table. And it won't be added but will be resolved in other ways.

We are working on improve admin console's experience, so that disconnection between contact and company won't cause any user experience impact.

To note, index not joined is only affecting listing contacts, it won't affect security or any other matter. Contact information is retrieved in conjunction with company, this can be seen in contacts list's flag at right side, it indicate whether company is inactive or not.

![2018-11-22_08h53_56](https://user-images.githubusercontent.com/1712143/48865347-3766e380-ee34-11e8-958a-f0c27952cc59.png)

From this image you can clearly see it indicate company active's icon is gray.
