### ISSUE TITLE
Forms - Add Export capability

### ISSUE THREAD

**Issue by Lowell-Syncrety** [DeskDirector/UserVoice#213]
Another "nice to have" request...  It would be great to be able to export the forms and have an import capability.  I'm trying to get another partner onto DeskDirector and I could export all my forms for him instead of him having to build them all from scratch.

Also could work as a rudimentary "backup"... export the form first before modifying.

**Comment by Nness** [comment]
@Lowell-Syncrety this functionality has been finished. It is on rolling out pipeline.

Once server version 18.61 is deployed, then you can use this feature. Since it is close to Christmas, the rolling out might be at start of Jan 2019.

If you want it ahead of time, simply contact support and tell them you want share form capability from server 18.61. Also the partner's name, so we can deploy to you and your partner earlier.

I will close this.
