### ISSUE TITLE
[8916] More Color Choices for Branding of DD Portal

### ISSUE THREAD

**Issue by PreciseNZ** [DeskDirector/UserVoice#23]
We need a color wheel for granular selection of element colors. E.g. Your "red" is not our "red" so our logo looks out of place. Adding a color selection/eyedropper would be fantastic!

I am aware of the thoughts to restrict users to 'themes' but I would really encourage additional debate around this given branding is such a major thing to many companies.

**Comment by notoli** [comment]
Sorry, I just added a very similar request under #38. Please add my vote to this request!

**Comment by Nness** [comment]
Is this request more towards color overall or just color on login page? What if we don't have any color choice on application itself, but allow login page to be fully configurable. Does that solves problem?

Currently application is using Material UI's color palettes, which will be hard to change, also in most of time, allow to change color in our application is currently cause trouble. Since the ability to change color is actually result unreadable portal. Its something we plan to remove in the future.

If following is how we designed portal v2, does that fit everyone's need?
1. Allow fully configurable login page. Include any color on background or even allow customer to provide their own CSS.
2. Inside application we have consistent color to give best user experience.
3. Remove in application big logo, but allow top left small logo. Customer can create black-white logo to put on navigation bar, or we can provide service to do that.

**Comment by stephenmonk** [comment]
I think it is very important that we are able to match the web portal (login and portal) as well as the applications to our colors.  I do understand that it can become complex for the downloadable apps, but I think part of why we want DD is to have our brand front and center.  We definitely have major issues with the login page colors, and then small issues with not being able to pick specific color codes to match our branding guidelines for the portal although we can get close.

I think removing the large logo and consolidating to the top bar only good again detract from our branding of the application.  Although, having a smoother look would not be bad.  Perhaps we can see some sample images of what you are proposing?  Or get a focus group for the proposed UI together we can participate in?

**Comment by Nness** [comment]
I am closing this for #76 and #77. 

To make sure we can perform backward support in the future, a proper colour system is needed. There is no shortcut for this issue, thus we have discussed possibilities and with two different approach to solve portal UI style.

Two approaches can work together.
