### ISSUE TITLE
DD Tech: Checkbox to make a note as 'Resolution'

### ISSUE THREAD

**Issue by PreciseNZ** [DeskDirector/UserVoice#24]

**Comment by Lowell-Syncrety** [comment]
... or Discussion.

**Comment by Nness** [comment]
ConnectWise have concept of ticket note and time entry, now a day inside ConnectWise, people can only use time entry to enter note. Is that what cause issue that note end up on invoice? @Lowell-Syncrety 

If that's the case, we can leverage ticket note concept instead of same as ConnectWise to use time entry for note.

**Comment by Lowell-Syncrety** [comment]
I'm missing something in your question.  In CWM we can add a note and have it be a Discussion, Internal Note, Resolution, or any combination of those if we wanted to... AND it can optionally be a Time Entry on top of any of those 3 types.  And then if we want it to be also sent in an email to the customer we check off their email address or add a new one.  All items tagged as Resolution will also show up in the invoice.  So sometimes I just want an item to be a Discussion (plus email so they get another way to read or reply) note and not show up as a Resolution and thus on their invoice.

For example, this might be a Discussion item with no time entry, and we want to email the customer:  "Hi, Jason, we are pretty sure we fixed your issue; could you test and reply back to this email and let us know if it's all good?"

This might be a Resolution and a time entry:  "Changed location where files were being stored, cleaned up hard drive space."

**Comment by Nness** [comment]
So from what you have said, either note or time entry, only resolution will get into invoice. Is that correct?

Basically, you want a way to control resolution flag?

Currently from functionality of our internal logic. We allow following combination.
* Discussion
* Discussion Resolution
* Internal
* Internal Resolution

Now it's matter of if our interface able to find a way to support that. The goal for interface is to decrease engineer's job, make them to create note or time entry as easy as possible.

As for the reason we only have above 4 combination, Discussion doesn't make sense to mix with internal. While we feel resolution is additional flag instead of flag of its own. A note should be either discussion or internal, then on top of that mark it as resolution.

If you believe that our understanding or approach have any issue feel free to point out. To limit only 4 combination makes user much easier to understand and config.

**Comment by Andrew-Lahikainen** [comment]
Resolution has been done and released. Discussion hasn't, I'll keep this issue open for now.

**Comment by Andrew-Lahikainen** [comment]
I think this has been addressed in the latest Tech release, the 4 combinations @Nness listed have been implemented.
