### ISSUE TITLE
[13816] Footer Customization on DD Portal.

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#247]
Feature request to place a footer at the bottom of all Portal pages to help clients have more option on how to communicate to us.

**Comment by Andrew-Lahikainen** [comment]
We're planning on designing a home/landing page for Portal where this information could be displayed when the user opens the app.

Another place we could put this sort of information is on the request support page. We already show the office hours there. This could lead to other features such as displaying a different number for out of hours.

I personally don't like the idea of adding this information as a footer to the app because it eats up vertical space which impacts all other page designs and can potentially cause usability problems, especially on smaller devices.

**Comment by Nness** [comment]
#231 
Footer is not good element for web application, it is suitable for web page. We consider this should be part of the goal for landing page.
