### ISSUE TITLE
Ability to hide .eml

### ISSUE THREAD

**Issue by NetFusionDesigns** [DeskDirector/UserVoice#251]
Re-opening this as the previous one requested the ticket be closed until the new interface is out. It's now 2019 and the new interface was released,  replies received via email within ConnectWise still attaches a .eml file visible to the end users on DD Portal.

Request to have this hidden or disabled as an option.

**Comment by Andrew-Lahikainen** [comment]
@NetFusionDesigns the new interface has not been released yet. We were not going to hide .eml files, we were going to make it so that they weren't so distracting (this applies to all file attachments). The reason is that sometimes the inline attachments of an email do not get attached to the ticket in CW/AT, so the customer loses information if they can't download the email.

**Comment by NetFusionDesigns** [comment]
Glad to here! – Thank you looking forward to the update

One of the other major complaints I get from customers is that the cant create a ticket on behalf of someone, it would be amazing to have this functionality –

In our cases, we find there is usually a “go to” individual at businesses that everyone reports their issues to, and that user ends up creating a ticket. When we provide customers with reports, they see the “go to” user having submitted 50 tickets, while everyone else has more reasonable numbers ☺



Geeshan Subasingha
NetFusion Designs Inc | Harnessing technology to grow your business

telephone:
Canada: 647.476.5259 x200
USA: 805.250.5214 x200

e: Geeshan@NFD.ca
w: www.NFD.ca<http://www.nfd.ca/>

GTA | 96 Main Street N, Markham Ontario
Tri-City | 22 Frederick St, Suite 700, Kitchener Ontario

[logo]
________________________________




This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error, please notify the system manager. This message contains confidential information and is intended only for the individual named. If you are not the named addressee, you should not disseminate, distribute or copy this email. Please notify the sender immediately by email if you have received this email by mistake and delete this email from your system. If you are not the intended recipient, you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited.

**Comment by Andrew-Lahikainen** [comment]
@NetFusionDesigns we're looking at implementing "create ticket on behalf of others", check this issue for more details https://github.com/DeskDirector/UserVoice/issues/54

Basically, we're going to allow certain contacts to edit the assigned contact on a ticket. So they create the ticket, then they change the contact on the ticket to the desired person. This is preferred over directly creating on behalf of someone because it records who created the ticket in the audit trail.

**Comment by prysmcorp** [comment]
We use the QuoteWerks integration. When we upload quotes and let clients know they're available in the client portal, we still get many customers that are confused and try to open the .eml attachment thinking that's the quote. Is there a way we could improve this? I know the conversation has circled around a few times as to whether to hide or not – last stance I see on it is a firm choice not to. If this is the case then what about a button that could appear based on "quotes" board and relevant tickets to direct the user to the correct area of the portal?

**Comment by Nness** [comment]
I believe the problem is why an email tell them quote is inside portal could lead to a ticket? That's not clear. 

The way I imagined on quote available email should be:
* Email sent **from** no-reply@xxx.com email
* Email contain deep link to the portal and tell user there are quote available for them to check out.

This way, there is no ticket involved.

The other thing that's unclear. Which is actual message inside email or the ticket. If just generic message says quote inside portal, then the question is like where?

Ticket is not designed for quote, I don't think this will be on high priority to remove eml file nor any setting. We do plan on improve ticket timeline UI, where make attached file more subtle.

**Comment by prysmcorp** [comment]
So workflow is this. Everything is a ticket in CW.

User generates a quote request through a request type in portal (specific to quotes board) or our team has entered a ticket in CWM onto quotes board. As quote is built out, time is tracked on that particular ticket. Once quote is available, a notification is sent to the customer from CWM on quote ticket to inform them of the quote. Problem is clients are accessing quote ticket, perhaps to respond with commentary, and this in turn leads some to want to download the .eml thinking it's the actual quote. (Often is the case too because users are attempting to download an offline copy of the quote.) You have to understand the majority of end users though do not realize what an eml even is.

I'll have to confirm if we're deep linking to quotes on ticket email notification. That could be part of the issue. Historically, I think we weren't able to deep link to quotes area of portal in particular.

**Comment by Nness** [comment]
You can link to quotes now. The knowledge base is [here](https://help.deskdirector.com/article/rb70qsabfd-portal-deep-linking#linking_to_the_quotes_list).

I think your feedback is valid, this give me some inspiration on how we can style the eml attachment inside timeline. e.g. once it's subtle, are we able to style it that people knows this is email archive? The more obvious the file is, the less we need an additional setting.

What we want to avoid is setting everywhere.

**Comment by Nness** [comment]
![image](https://user-images.githubusercontent.com/1712143/86202540-96670f80-bbb6-11ea-9f66-dd2999ad2fef.png)

This uservoice should count as resolved. We just released improvement to ticket timeline, where attachments have different display compare to note, and for EML file, it is much subtle compare to image file.

**Comment by prysmcorp** [comment]
Love ❤️ this! Much better and I believe our users will appreciate the improvement. Thanks @Nness
