### ISSUE TITLE
[14154, 19345] Display Parent/Child association of tickets within DD Portal.

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#259]
Current functionality is available to hide/show child tickets within DD Portal.

Feature request to have this visually available in DD Portal, with child tickets showing as a part of or linked to the parent ticket in some way.

Example of visual reference from within ConnectWise:
![image](https://user-images.githubusercontent.com/30588784/53395789-9c1f7480-3a07-11e9-8534-16c590d9d5d6.png)

**Comment by awiedeman** [comment]
If on the left side bar, there would be a field visible that shows the parent ticket number. Added bonus if it is a clickable link that takes you TO the parent ticket!

**Comment by awiedeman** [comment]
Hi DD Team - Is this something that is remotely possible to do? Perhaps showing a "Tree" of relationship between the parent and child tickets? One that is maybe clickable to go into the ticket?

In the meantime, our clients have asked us to put a note/email through the ticket EVERY time we bundle a ticket because they just don't know what the new parent ticket is - and I can understand.  Thanks!

**Comment by Nness** [comment]
Currently you can turn off display of child tickets. To do that, head to admin console then dive in from left side menu:
1. expand `System` menu group
2. Select `Feature Configuration`
3. Select `Tickets` tab.
4. Scroll to the bottom, where `Portal` section is.
5. Enable `Ignore child tickets`.

That way your customer won't be able to see child tickets at all. 

Technically, it is possible to display parent tickets.

**Comment by awiedeman** [comment]
I understand that but the thing is they want to see it and also understand
what child tickets there are. So rather than disable, we want to give them
MORE visibility. Make sense?

Ashley Wiedeman

**Comment by joeseppie** [comment]
Techs need to have the visibility of all child ticket notes while working out of the parent ticket.  We aren't yet working tickets out of DD Tech because of a handful of missing features/functionality like this.

Our goal is to have techs working tickets out of DD Tech and not have to use the CW Manage ticket screen at all.

And from the client side, yes, they should be able to see that their ticket is a child of another ticket.  The more communication/info we give them about how their ticket is being handled, the better.

**Comment by Nness** [comment]
@joeseppie for TECH, there is another user voice. #413
