### ISSUE TITLE
Client facing download urls

### ISSUE THREAD

**Issue by PreciseNZ** [DeskDirector/UserVoice#26]
In situations where clients must give their end-user a download link for the portal, they currently have to give them: 
https://downloads.deskdirector.com/[mspRavenName]/[FileName]
 
Clients would rather give end users something like:
https://portal.[customDomain].com/downloads/client/[FileName]
 
This could be implemented by a simple redirect (although the download url would remain as downloads.deskdirector.com)

**Comment by Nness** [comment]
There is issue with public available links, which in the future we will not providing such link.

In the future, all downloadable link will be generated on demand. One of solution is to allow download from portal. Which is stated inside #344. 

As such, I will close this issue. Since it is no longer relevant.
