### ISSUE TITLE
[14321] Live DD Portal Updates

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#265]
Feature request so DD Portal refresh/reload isn't required for ticket updates to display.

**Comment by Nness** [comment]
This is planned feature and only available for customer who purchased chat and notification package.

**Comment by rmanueldd** [comment]
related ticket: 49450

**Comment by Nness** [comment]
This has already been implemented. The ticket 49450 has nothing to do with this. And we will never implement auto refresh tickets if that make sense. 

The ticket 49450 is about TECH portal's ticket list doesn't auto refresh. Any well designed application such as Twitter, GitHub issues will never auto refresh on the tweet list or issue list. Since it represent the view at the time of retrieval. It doesn't matter how long you are looking at it, it should reflect the result at the time of retrieval. If any time refresh, it will cause inconsistancy.

Unless a UI is designed to only design latest data, else auto refresh shouldn't be even exist.
