### ISSUE TITLE
DD Tech: Improved Contact Search

### ISSUE THREAD

**Issue by Lowell-Syncrety** [DeskDirector/UserVoice#289]
I love how the searching in DD Tech throughout is so fast, and that there is a Contact Search. Going to use this a lot, especially in sales, where I'm trying to find a contact's email address quickly.

The search-as-you-type is great but sometimes confusing. If I search for "Ed" for example, I have 3 contacts with that first name but excluded is the one contact I'm looking for, "Edward".  When I add more, "Edw" nothing shows up, not until I type "Edwa". I can give other examples, but just curious as to why this is.

**Comment by Andrew-Lahikainen** [comment]
@Nness or @DDAndyChen  you would be able to give a better answer than I can.

**Comment by Nness** [comment]
I checked your instance, search seems fine. Since Edward is result of prefix search, it come after exact match. The name exactly match Ed came before any prefix match.

Since there is delay on notice this user voice, things may changed. I will close this. Feel free to contact us if this is not the case.
