### ISSUE TITLE
[10235] Add a way to quickly open a ticket tab

### ISSUE THREAD

**Issue by Andrew-Lahikainen** [DeskDirector/UserVoice#3]
Currently, users must make sure their board and company filters are correct, search for the ticket number, and then click on the ticket. We could make this faster.

One way would be to add a button at the end of the open tabs. This button would allow users to add a ticket by id, regardless of their filters. This is similar to how Zendesk tabs work.

![image](https://user-images.githubusercontent.com/10571313/41388799-b9c5d060-6fe1-11e8-859b-5afc71469774.png)

**Comment by Lowell-Syncrety** [comment]
This is also the way that Staff HUD currently works; quick and easy to add a ticket number, though my recommendation as it was for Staff HUD (not implemented) is to leave it an open field so I click into it, CTRL-V or type the number and hit Enter, and the ticket shows up.  In Staff HUD it's an extra click to open that field, oddly because there's a ton of visual space where it could just be an always-visible field.  We use that field a lot.

**Comment by Andrew-Lahikainen** [comment]
My preference would be to avoid having a field that is always visible. Just because tabs in Tech aren't just ticket tabs. They can hold contacts, companies, and who knows what in the future.

To me, this seems like a power user feature, perhaps a hotkey combination could be useful here.

E.g. to open a ticket tab, press ctrl+alt+t. This would open a dialog with a simple text box which would automatically be focused. Hit ctrl+v and hit enter.

**Comment by Andrew-Lahikainen** [comment]
This has been shipped (only available for ConnectWise users at the moment). I'll keep this issue open until Autotask has been completed

**Comment by Lowell-Syncrety** [comment]
Nice! Thanks for the update @Andrew-Lahikainen.

**Comment by Aycorn** [comment]
This has since been implemented in the Tech Portal:

![image](https://github.com/user-attachments/assets/7db08a26-bf8f-4267-8465-266109dde2eb)

Closing.
