### ISSUE TITLE
[9170, 14863, 22844] Add support for time entries and creating new tickets for Autotask

### ISSUE THREAD

**Issue by Andrew-Lahikainen** [DeskDirector/UserVoice#4]
Tech for Autotask does not support creating a ticket or creating a time entry. Currently we must link out to Autotask, but this has its own set of problems. Autotask has several instances with unique urls, and since the url is built on the client side, our redirect does not work for some people.

The completion of this issue will solve this problem.

**Comment by Andrew-Lahikainen** [comment]
Create ticket has been deployed

**Comment by Nness** [comment]
* `AllocationCodeId` also known as `BillingCodeId` in RESTful API. This is similar to ConnectWise work type
* `RoleId` This is required and should provided as dropdown.
* `Type` This is static and is not necessary required. We can check out pickup list and choose ticket type.

### Role
Each resource has default role ID. They can be default value but need to be verified against role.

Role and Resource relationship has been recorded under [ResourceRole Table](https://www.autotask.net/help/developerhelp/Content/AdminSetup/2ExtensionsIntegrations/APIs/SOAP/Entities/ResourceRoleEntity.htm). It included following.

- Active
- QueueId
- ResourceId
- RoleId

Only Active Role that with equal QueueID or QueueID that's null can be used for ticket. Of course resource ID also need to be matched.

Our system should sync [Role Table](https://www.autotask.net/help/developerhelp/Content/AdminSetup/2ExtensionsIntegrations/APIs/SOAP/Entities/RoleEntity.htm). To provide fast access. Since it does not have last update time, we should keep it up to date every hour.

Each resource have its own Resource to Role relationship. Where we should catch them in hourly based. Where we can save the relationship into resource config. 

### Allocation / Billing Code.

Allocation may be different between each resource. Some of them may seen less options than other. Thus, we should cache this for an hour for each resource.

### Approach on resource related option caching

We should cache resource related option within our database. Here is logic on how to and when to refresh it.

```
const cachedOption = await database.getResourceOption(resourceId);
if(cachedOption != null && cachedOption.lastPoll < 1hr) {
  return option;
}
const option = await autotask.getResourceOption(resourceId);
if(option.isError()) {
  return cachedOption;
}

await database.saveResourceOption(resourceId, option);
return option;
```

**Comment by DDAndyChen** [comment]
To enable resource impersonation when adding time entries, the **Allow impersonation of resources with this security level.** need to be enabled in Autotask. See https://ww2.autotask.net/help/Content/AdminSetup/1FeaturesSettings/ResourcesUsers/Security/Settings_WSAPI.htm
