### ISSUE TITLE
[21539] Added functionality for Parent/Child tickets within DD Tech

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#413]
Currently there is no indication of parent/child tickets while working with DD Tech.
Feature request to:
1) Display parent/child ticket hierarchy and quick link to ticket as required.
2) Add the ability to remove a parent/child link. This is done with the following option in ConnectWise:

![image](https://user-images.githubusercontent.com/30588784/73216417-0f96ac80-41aa-11ea-885c-cba449d88f0f.png)

**Comment by Aycorn** [comment]
Similar Request: Service Ticket #22131 - In the DD TECH portal we are seeing CHILD tickets listed and would like to only show PARENT ...

**Comment by Aycorn** [comment]
Similar Request: Service Ticket #22165 - DD Tech HUD appears to show merged or deleted tickets

**Comment by joeseppie** [comment]
@Nness thanks for the link to this issue.

From my post in the DD Portal issue:  Techs need to have the visibility of all child ticket notes while working out of the parent ticket. We aren't yet working tickets out of DD Tech because of a handful of missing features/functionality like this.

Our goal is to have techs working tickets out of DD Tech and not have to use the CW Manage ticket screen at all.
