### ISSUE TITLE
[21854, 22103] Portal ticket list improvement

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#438]
* Facet on open, closed ticket count
* Filter on priority
* Filter on contact
* Friendly date time
* Priority display
* List item display improvement

**Comment by Aycorn** [comment]
Further to this, potentially consider this happen automatically is the contact has no open tickets? Small tooltip prompt along the lines of "There are currently no active tickets to display, both open and closed tickets will now be displayed"

**Comment by Nness** [comment]
Personally, I drive more towards GitHub's design. Given example below. 
![image](https://user-images.githubusercontent.com/1712143/77468672-c80f6280-6e72-11ea-823c-5f15e68fbd55.png)

Compare to our approach.
![image](https://user-images.githubusercontent.com/1712143/77468730-dcebf600-6e72-11ea-98c2-740d3279181a.png)


Which one you can easily tell there are tickets? Also, since we have so much space why not use it like TECH does?

![image](https://user-images.githubusercontent.com/1712143/77468805-fee57880-6e72-11ea-92ac-085067a5179a.png)


We can achieve different look based on device size. For medium to large, we can have left panel display facet or filter like TECH, while in small screen, we can try other approach. 

If we display `open/closed` by default, people might always have to filter to open tickets. Numeric indicator can resolve that I believe.

**Comment by Nness** [comment]
Ticket list improvement required.
* Friendly date time similar to TECH
* Use square avatar to decrease line height.
* Open/Close indicator
* Facet at left side during medium screen.
    - My Ticket, All ticket Filter
    - Open / Closed / All facet
    - User tickets facet when `All tickets` been selected.

**Comment by Aycorn** [comment]
Similar Request: Service Ticket #22103 - Sorting Ticket List

**Comment by awill4457** [comment]
Could the portal also get the ability to filter by status, like you can filter by contact.
Otherwise, in the search, allow for statuses to be searched?

**Comment by Nness** [comment]
Majority of the improvements on this issue has been resolved, except filter by priority. Majority of user can only see their own tickets, or not a lot of open tickets. Thus, the importance of filter by priority is questionable. Close this for now,  until filter by priority been raised again.

As for status, not in consideration as long as we support ConnectWise. The problem with ConnectWise is status is defined per board level. Filter by status only make sense if anyone is looking tickets at board level.
