### ISSUE TITLE
Option to make Date Picker always visible a form rather than drop down menu

### ISSUE THREAD

**Issue by justinDJC** [DeskDirector/UserVoice#463]
We're finding that our forms look much better when we avoid using the drop down menus.

This might be a symptom of the dropdowns not looking sexy, but we find the user experience is much nicer when all options are available.

Could we have an option for the Date form module to 'Always show' rather than be a drop down!

It would look much nicer :)

**Comment by Nness** [comment]
Currently we are using material UI. In the future we want to move away from it. Since many of portal component no longer using material UI, other than form.

It is true that radio button or check box should always be used unless the list is too long. 

For date, it is possible but on the other hand, the dropdown itself can be improved. Let's don't rule the improvement out just because current dropdown looks ugly.

Our priority will be restyle form interface first, then consider this.

**Comment by justinDJC** [comment]
Thanks for the response! Lookin forward to see the new designs :)

**Comment by Nness** [comment]
This has been addressed
