### ISSUE TITLE
[23320, 23713] Allow selecting multiple technicians in ticket filter view

### ISSUE THREAD

**Issue by akkiogra** [DeskDirector/UserVoice#471]
We’d also like to be able to select multiple technicians. Currently you can only select a single technician to view their assigned tickets. We’d love to be able to select multiple technicians and filter showing only those technicians or a combination of Assigned technician specifically with all other unassigned tickets. I think this would allow quicker and handier uses of the filter without going outside of your philosophy of streamlining a system.

**Comment by dustinabingham** [comment]
From an administrative perspective, this would allow a supervisor to check on a particular set of individuals simultaneously or a team over a particular customer, easily. Rather than having to go through techs one by one. Not to mention, from a tech side, this would allow a team to view their fellow teammates quickly for a particular customer AND be able to see unassigned tickets quickly to help out non-dispatcher based Remote teams.

**Comment by Nness** [comment]
This has been implement alongside of unassigned ticket filter. It should deployed to everyone at early Jan. It require server update, which been sealed during Christmas and new year period.

The change allow to filter by ticket assigned to any of technician that's been selected. 

In the future it is possible to add functionality to change behavioiur. (from default contain any to contain all)
