### ISSUE TITLE
[24144] Consistency between ticket list UI and ticket details

### ISSUE THREAD

**Issue by iskolares** [DeskDirector/UserVoice#512]
The pending update to tech portal (on staging) has moved ticket contact/details into the right, but on the ticket list page, the ticket filter pane has remained on the left. On the current version, both are in the left.

Ticket List page:
![image](https://user-images.githubusercontent.com/13637718/101087847-b4c6b080-3617-11eb-8762-6ec2a37a3d76.png)

Ticket details page
![image](https://user-images.githubusercontent.com/13637718/101087754-8cd74d00-3617-11eb-8e13-bb37974e576e.png)

The customer is asking, for UI consistency, to have both panes on the same side (either left, or right for both).

**Comment by Nness** [comment]
This is placeholder and won't be changed.

UI consistency shouldn't applied here. Two completely different page has no relationship on consistency.

The reason when switch view and there is no visual impact it is because there is **no relationship** between two. 

On top of that, the scenario is different for both page.

**Ticket List**
When enter ticket list page, the focus is on **filter** and **today's ticket count**

**Ticket Timeline**
When enter ticket detail page with timeline, the focus is on **timeline** and shouldn't on ticket info.

For left to right culture, such as western culture and modern asian culture. The focus for normal user is on the left. That's the first location people will focus at after landing. Human brain will process left to right before the common knowledge such as ticket info position. 

Decision to swap ticket info to right side is to decrease initial focus and make it subtle.
