### ISSUE TITLE
[25121, 26055, 26063, 26102, 26056] Allow Additional Email Delivery Option

### ISSUE THREAD

**Issue by iskolares** [DeskDirector/UserVoice#547]
Customer is asking if they can setup multiple email delivery mailbox options, this way they can send as a different email address for different server hosts, 

For example, for sample.customdomain.com server host, they would like to connect it to an email like support@customdomain.com mailbox, allowing them to send all email as that identity, without affecting all the other host setups for their instance.

**Comment by iskolares** [comment]
Related ticket #26055

**Comment by iskolares** [comment]
Related ticket #26063

**Comment by iskolares** [comment]
Related ticket 26102

**Comment by iskolares** [comment]
Related ticket #26056

**Comment by MattDunn12** [comment]
This would be great for us to fully utilise Desk Director with multiple service boards, to allow emails in different boards aswell, e.g. Sales board could use Desk director to send out emails using sales@ , Project board for projects@ rather than it all going through support if we were to do this currently.

**Comment by Nness** [comment]
We have already started this one week ago. Expected to be ready 2~3 weeks later.
