### ISSUE TITLE
Improve ticket info column to avoid push detail to bottom of page

### ISSUE THREAD

**Issue by bur4an** [DeskDirector/UserVoice#551]
It easier to quickly update the ticket status if it is on the top rather than having to scroll down.
![ConnectWise_GziyvojWqx](https://user-images.githubusercontent.com/17839903/115292661-62db8d00-a1aa-11eb-95d1-3a26fde98ce4.png)

**Comment by Nness** [comment]
User, company info is still far more important than those. Yes it can speed up on modify board, type, sub type. But without  good exposure of company and ticket owner, I wouldn't see this as good UX change.

Type, sub type normally only change at ticket creation, where status you can change when you add note or time entry.

**Comment by Nness** [comment]
After evaluation, this user voice is very misleading.

* User's goal is to see ticket detail without scroll
* Cause is because of ticket info column's design. Ticket owner and many other UI component took too much space, which push ticket detail to the bottom.

The improvement is coming.  It should be deployed within next 2~3 days.

**Comment by Nness** [comment]
This is done and released.
