### ISSUE TITLE
[25403] Sort out OAuth verification

### ISSUE THREAD

**Issue by iskolares** [DeskDirector/UserVoice#559]
Currently, when customers use OAuth, the portal will appear as "unverified" on the O365 prompt.
![image](https://user-images.githubusercontent.com/13637718/117590571-45d02380-b184-11eb-9699-abe7ced68f24.png)

Needs to sort out verification from our end.

**Comment by Chrispe66** [comment]
This issue is with how we program the app registration at the top level. I have had to start the process of acquiring an MPN applicable to app registration so that I can add it and then it will be verified. This was a requirement recently added to Microsoft on June 1st I believe.

**Comment by Nness** [comment]
We will provide DeskDirector default application to be used for client portal. For people who want their own branding, they will have to go through the verification themselves, nothing we can do to help.

Microsoft will require D-U-N-S number, similar as Apple store.

**Comment by Nness** [comment]
For people who don't want to register app for their own branding but use generic brand, you can contact with our support, we can setup for you. In the future it will be available through admin portal.

**Comment by Chrispe66** [comment]
So the solution is to remove my logo and then all should be verified?

**Comment by Nness** [comment]
No. to use the application DeskDirector have registered. Which at current stage does not have logo and with generic name of `IT Now`. 

You can contact support, which our support can switch your instance to use DeskDirector's application. That way OAuth should be functional.

Else you have to go through verification with Microsoft, such as D-U-N-S number etc. Which will take long time. Unless you are desperate want your brand there. Else contact with our support is fastest way.

**Comment by Chrispe66** [comment]
This is not as hard as people may think. When I went to start my DUNS it was already there because I had been in business for a while. Even though I am a Canadian business, it was still there. I verified my account, and I was good to go. Then in Azure, I had to set up, in the Partner portal, MPN section, the Tax and Payout profiles. This took about 2-3 days. I then took my Developer MPN and just applied it to my Registered App, logged in as a new client user and look at this:

Verified!

![image](https://user-images.githubusercontent.com/77400501/121450705-41a54a80-c96a-11eb-81ff-401aa3ca6ef5.png)
