### ISSUE TITLE
Ability to filter learning items by Company/Contact

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#56]
Currently the only filtering system available for learning is by Category.
(Manage Learning > Category XYZ > Filter)

The same functionality per learning item would provide flexibility and reduced some cluttered categories.
(Manage Learning > Category XYZ > Learning ABC > Filter to Contact/Company)

This could be introduced as a separate option per learning item, or under the current "Edit" window.

**Comment by Nness** [comment]
This won't be considered.
1. learning is already marked as deprecated
2. We are planning on new portal menu system, that one will allow a more flexible system.

**Comment by Nness** [comment]
We will share out design work in near future.

**Comment by Aycorn** [comment]
Similar Request: Service Ticket #13710 - Learning Center Permission on a Learning Item

**Comment by Nness** [comment]
I need to be clear on this request.

**learning is already marked as deprecated**
The reason for this to be reject is not only learning is deprecated, it is this idea have fundamental problem. 

Scenario 1: Category A can be seen by Company 1, then it only has 1 item and that item has filter says only company 2 can see this. Now what?
Scenario 2: Category A can be seen by Company 1, it has 3 items and one of them has filter says only company 2 can see And? Can company 2 see this category?

This feature introduce complexity that it is so hard to manage. Even learning is not on deprecate category, I will still reject his request. 

On the other hand, what's compelling reason to introduce customer specific learning material? For example excel tutorial have 3 courses, and by add 4th one for a specific client does that means other customer doesn't have to see that? 

If we want to tailor to that degree, should I say the whole learning system should be tailored to a specific style? For example, recreate learning center for each customer. Each one has different category order, so that user can easily find the topic they are interested at.

Now, is the problem with filtering or is the problem with finding the content? If finding content is much easier to achieve, then there is no need to limit certain content can only be seen by certain customer. Is that correct? So the root problem is searching rather than limiting?

**New menu system**
New menu system is coming but it won't alter learning center. It only means customer can create their own learning system and filtering. In most of case, this will hardly be the case. It only introduced possibility.

**Improved learning system**
This has not been settled. For now planned feature is use OneNote as source content material. This still have same issue on filtering. That means configuration is per notebook. There is no such thing as micro management will be introduced.

**Comment by NetFusionDesigns** [comment]
Here are some use cases. I think a good case could be made for having customer specific documentation, example : Guest WiFi, Connecting to VPN, Resetting passwords


Personally I would like to see a structure similar to what's available on Request Types:
Here is an example:
Learning Center
->Office 365 (Category seen by all customers)
->Mobile Phone Setup
---> Android (Office 365) -  Visible to All - Except Customer A, B, D etc.. ( same way request types are setup)
---> iOS (Office 365) - Visible to All - Except Customer A, B, D etc.. ( same way request types are setup)
---->Android (CustomerA) - Visible to only Customer A - this is an example of a customer who does not use Office 365 and their mobile setup is different)
-> Guest WiFii (Visible to all)
----> CustomerA WiFi (Visible to Customer A only)
----->Customer B WiFi (Visible to Customer B Only)
etc...

**Comment by Nness** [comment]
This feels like micromanagement. Sure some of setting might be different, shouldn't that be company specific configuration set? Else one of thing could be introduced with above setup is empty category. Where all the child elements are not accessible.
