### ISSUE TITLE
[25642, 25661, 25703] Bring back Ticket Status to Client Portal on new UI

### ISSUE THREAD

**Issue by iskolares** [DeskDirector/UserVoice#565]
With the recent UI update for client portal, Ticket Status was removed. These customers are asking if it will be reinstated.

It comes handy for quick glances for clients to see what the actual status is of the tickets they have submitted, instead of opening each tickets to view the status.

**Comment by Chrispe66** [comment]
Just to clarify, you are asking for it to have a column in the Ticket list so you can sort or view (possibly filter) by status?

I think, overall, it would be nice to have the ability to add or remove columns in general.

**Comment by Nness** [comment]
To explain what's happened.

## DeskDirector client portal showing status in ticket list.
No, not exactly. We do show status in our first iteration inside WPF client way back 2012. Then removed later in web version. 

4 weeks ago, we added status back to ticket list temporarily, because we removed last ticket note from ticket list. (As some customer complain not 100% accurate, only 99% accurate).

1 week ago, during ticket list redesign, we have removed it again in favor of assigned member and request more info.

## What is the reason status not have high priority in client portal?
Status's usefulness depends on how well MSP name it and how well MSP use it. Many time it is noise. Especially Autotask and ConnectWise allow customize status. Where people create very long status name.

Such customization cause difficulty on displaying them. 

If you take look at Zendesk, their ticket status is not customizable and fixed. It is just `new`, `open`, `pending`, `on hold` and `closed`. In such way it is very easy to display inside ticket list. They use tag to add flavour to the state.

## Will DeskDirector display status inside client portal?
DeskDirector client portal will show status if UI/UX is suitable. Such as ticket detail page.

2 days ago, we have an minor release, where status will display when you mouse over ticket subject inside ticket list. It is general available now. Which @Chrispe66  you can check and verify.

As such, I will close this ticket. In the future we will continue to improve  our UI/UX both at client portal and TECH portal. We will include if make sense.

**Comment by Nness** [comment]
We have just made additional improvement on top of hover. It should be general available within an hour or so.

### Hover
![firefox_Ll4wiUzQqj](https://user-images.githubusercontent.com/1712143/121453511-672b6600-c9f5-11eb-9a99-0207b3b33824.png)


## Status - same as assigned icon, will display above iPad device size
![firefox_9xZYrPoiMV](https://user-images.githubusercontent.com/1712143/121453521-6c88b080-c9f5-11eb-9978-c207c71dd509.png)

**Comment by Nness** [comment]
Example for the reason that have status been removed in redesign. `In Progress - Do Not Send Email` as status name.

![image](https://user-images.githubusercontent.com/1712143/121458201-10298f00-c9fd-11eb-8863-e54e85c4e14d.png)
