### ISSUE TITLE
[20558, 25282] DD Portal: Block user access

### ISSUE THREAD

**Issue by PreciseNZ** [DeskDirector/UserVoice#58]
Would like an option to be able to block users access to DD portal without being inactive in CW/AT.  Use case is a contractor or end users that shouldn't be creating tickets without going through a primary contact.

**Comment by Cmatthewman** [comment]
I'd also find this useful. In a case of schools, we want teachers to have access but not students.

**Comment by Nness** [comment]
Some of our customer want to block ticket creation not portal access

**Comment by Aycorn** [comment]
Similar Request: Service Ticket #23947 - Inactive users can login

**Comment by iskolares** [comment]
Related Service Ticket #25282

Cust is asking to have an option to select which users from a company are allowed/denied to login to the client portal

**Comment by IamBlackmonty** [comment]
Related Service Ticket #25282 was mine.

Having just implemented oAuth it allows all users to access the portal.  It would make it way easier to deny access by default at the global and company level then add an allow by contact.  Disabling the contact in the PSA is not an option.  And because we would like to have our custom domain appear on our website, it only makes sense to have it restricted

**Comment by Nness** [comment]
@IamBlackmonty Thanks for detail out reason. One thing I don't get it is, even when you put on your website, it doesn't means you have to restrict by that kind of level.

You might not aware we have several restrictions.

1. Portal access, by specify company type and status for which company can access portal.
2. Contact auto creation's rule. You can specify not to create new contact if given user is not exist.
3. Email domain, if email domain not registered with a given company, then, no new contact will be created for that domain.

Your scenario didn't explain why exist setting cannot satisfy your need. 

If an already exist contact log an ticket through email connector, do you want to block him from access client portal? Your scenario pretty much says, even an exist user have ticket with your MSP, he may not have access to client portal unless you allow them to. Is this what you after? If so, why?

**Comment by IamBlackmonty** [comment]
Hi

All 3 restrictions below will not work.

For example.  I have a company with 250 users.  Only 2 users are allowed to log tickets.


  1.  I cannot restrict by company type or queue as they need access
  2.  Contact auto creation rule has no bearing in this situation
  3.  Again, creating new contacts has no bearing

So in the example above, the support portal will be accessible by all 250 users.  Yes, the other 248 users could email our support queue to create a ticket but with this companies policy, that is not allowed.  Even if they did log a ticket, they do not have any access to the Autotask portal to look at the ticket or other tickets etc.  This is enabled individually by contact.

Craig



Craig Wallace
Systems and Training Manager
P02 4940 1800oas.com.au
75 Shortland Esplanade, Newcastle, NSW, 2300, Australia
NEWCASTLEMUSWELLBROOKCENTRAL COAST

**Comment by Nness** [comment]
This is related to user voice #134. It is mainly point of contact, rather than block user access.

**Comment by Nness** [comment]
@IamBlackmonty I have closed this user voice in favor of #134. As point of contact is more in line of what you have asked for. Block user access is a bit of misleading.

If 250 users can login into portal, can view tickets, can reply to tickets, but they cannot create ticket. Then this issue is essentially resolved, also with good advantage, where they still have ability to view tickets, and view other resources.

**Comment by Nness** [comment]
@IamBlackmonty will approval fit with your case. Where those 248 users's ticket will landed as approval required, where that 2 users have to approve before proceed.
