### ISSUE TITLE
[25958] Ability to filter tickets both "Assigned to Me" and "Unassigned" (TECH Portal)

### ISSUE THREAD

**Issue by iskolares** [DeskDirector/UserVoice#582]
In the TECH Portal currently, techs are able to filter tickets based on:
"Unassigned"
"Assigned to Me"
"Select"
![image](https://user-images.githubusercontent.com/13637718/125000928-94773c80-e0a5-11eb-9d88-6b40401626ef.png)

Cust wants to be able to filter both "Unassigned" and "Assigned to Me" together as their main concern when logging in to the Tech Portal is handle tickets they own and those that are not assigned to any tech yet.

The "Select" option presents the ability to select multiple techs, including the tech's own name, but there is no option for "Unassigned".
![Screen Shot 2021-08-23 at 8 19 32 AM](https://user-images.githubusercontent.com/13637718/130368939-836ced6d-2a03-4aef-9368-a95e7d01fb9c.png)

**Comment by Nness** [comment]
This user voice has been addressed by using different approach in TECH portal 1.40. 

Instead of showing unassigned tickets and tickets assigned to me, we provide live dashboard to display count for both. Live dashboard will update every min or when filter change.

Allow display two filter collection together is not an solution, since it depends on how many unassigned are there. It removes focus and make TECH portal harder to use. The more unassigned tickets you have, the harder you can navigate around tickets assigned to you.

Dashboard provide count not only display current state, also is a way to tell whether new tickets arrived or handled. It also provide fast way to switch between two collection, since our query is very fast, such approach is best to suit with our application.
