### ISSUE TITLE
[25180] Add indication of primary contact in admin console

### ISSUE THREAD

**Issue by iskolares** [DeskDirector/UserVoice#584]
In the Tech Portal, it looks like this:
![image](https://user-images.githubusercontent.com/13637718/125860456-dffb9317-2292-469c-ae1a-96d2c5fd98f5.png)

However, there is no indication of such in the admin console. 
![image](https://user-images.githubusercontent.com/13637718/125861044-63e51265-42c5-4fc7-985d-d47f036ee466.png)

It will be best if it can be added to the admin console too, and possibly also the indicator for VIP and Approver too?

Last thing is add a filter in the admin console for the Primary Contact in the Contact list? VIP and Approver can be filtered out using "Permission Config Overwrite", but no way to filter out Primary Contacts yet.
![image](https://user-images.githubusercontent.com/13637718/125863697-bacbfb5c-c42b-4743-a2de-5ef537eabc30.png)

**Comment by ColoradoNative** [comment]
This is a significant need. The Primary Contact flag is great, but we'd like to see additional CW Contact Types imported into Desk Director.  This is where we manage client metadata: VIP, InternalIT, DecisionMaker, etc. We also need the ability to target an Email Broadcast to these Contact Types.

**Comment by Nness** [comment]
We already displaying primary label inside contact profile. I will close this.

As for @ColoradoNative , currently we have no intention on use contact type for anything, you can contact with our support, depends on your subscription, we may offer free migration, where one off sync contact type to our system as tag. Then in the future you can continue to utilize on tag rather than contact type.

Soon or later we will offer tools to better manage tags, to make tag an go to tool. I have added two user voice regarding tag management. #600, #601.
