### ISSUE TITLE
Single click for "Click to paste images from clipboard" field

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#585]
Can we make the **Click to paste images from clipboard** field pre-clicked when you select the option? I have to click this, and click into the field again before pasting.

![rucyICtUjm](https://user-images.githubusercontent.com/30588784/126589008-6201e340-4a6d-4b96-b589-8f9447b159a0.gif)

**Comment by Nness** [comment]
If remove copy paste then this problem is resolved. I do aware of the issue. The problem is how we can achieve it.

In javascript, you can only paste on things that you have focus on. Normally other application only support drag & drop or click to add attachment. Not copy paste.

Copy & paste is only available for things that has text field or input. Where you can focus and visual state of focus.

@Aycorn , if you have seen anything with copy paste that's not involve any input or text area, let me know, I would like to check out. Or if you have any better solution actually works.

Since I'm struggling to came up with alternative. I notice it when I improved add ticket note page before.

**Comment by Nness** [comment]
This has been improved in client portal 3.23. Check admin portal for more detail.
