### ISSUE TITLE
Portal Contact Navigation Incorrect

### ISSUE THREAD

**Issue by IamBlackmonty** [DeskDirector/UserVoice#590]
When in a company, then navigating to contacts if you hit the contacts link it takes you back to the 'All Contacts' list and not back to the specific company contact list

![Contact Navigation](https://user-images.githubusercontent.com/83567079/128100366-b0f3bd4e-f8de-4d10-99ee-df14daeed6df.jpg)

**Comment by Nness** [comment]
This is known issue, which we will eventually address. Contacts was not under companies before, they have their own route.

In the near future, the companies for TECH portal should be well designed to not have such issue, where admin side will be adjusted when it can be easily refactored. 

To get around, you can click on company instead of contacts.

Since companies, contacts was coded at start of new admin portal, there are some technical debt we have to pay which is the reason blocking from moving forwards. It can be done, just balance on the time to spend on new feature and time to spend on adjustment.

**Comment by Nness** [comment]
This has been resolved on staging. To check on staging, change admin route from `admin/v2/home` to `admin/staging/home`. 

Change include following.

- [x] Allow contact route to be under company route. e.g. `companies/:companyId/contacts/:contactId/profile`
- [x] Only display company inside breadcrumb if under company route.
- [x] Ensure contacts list can navigate to it's child route, rather than contacts route.
