### ISSUE TITLE
Feature Request: Ability to Display Pictures within Forms

### ISSUE THREAD

**Issue by Magnum901** [DeskDirector/UserVoice#591]
You can currently link pictures within DeskDirector Forms, but it would be great if we had the option to embed an image as well.

**Comment by Nness** [comment]
You can use markdown inside field description to display images. Following as an example. We might support upload image at some stage, but no promise can be given at this time. Since it is good to have.

```
![image title](https://image-link)
```

I will close this user voice for now, if you think it is something different, you can submit ticket to our support, they can help you adjust this user voice.

We do prefer user voice submit through our support, where we can better understand your needs.
