### ISSUE TITLE
[26178] Additional admin console role

### ISSUE THREAD

**Issue by iskolares** [DeskDirector/UserVoice#594]
Cust is asking if an additional [DeskDirector role](https://help.deskdirector.com/article/zcr6mh1zst-tech-roles-and-permissions) can be added that is specific for account management. 

This role would only be allowed to set/manage permissions for contacts/companies. Currently, only admin and master admin is allowed to manage permissions for contacts/companies, which grants them access to more areas in the admin console.

**Comment by Nness** [comment]
Admin is designed for manage permissions for contacts and companies.

**Comment by Nness** [comment]
@ColoradoNative The admin role is designed for customer manager role. Below is image showing what they can access. Anything under portal means client portal. Where it either related to interface setting or permission setting.

Intentionally, we don't want to introduce any configurable role, which that will cause config nightmare.

We might allow some of setting to be exposed to advanced member at some stage, when we slowly restructure TECH portal. We will also introduce audit log later this year to help management of setting. To provide record of who changed what.

If you can detail out more about your concern with current admin role that will be helpful. Else I will leave this user voice as closed. Since technically admin is for what this is after.

![image](https://user-images.githubusercontent.com/1712143/129103660-650c93af-63a0-484a-8fd9-cf1c6efdb32d.png)
