### ISSUE TITLE
[26659] Add distinction to "Something else"

### ISSUE THREAD

**Issue by iskolares** [DeskDirector/UserVoice#622]
Current implementation of "Something else" makes it a bit too "camouflaged" to the request types.

Adding a bit of distinction will make it pop a bit, so customer can scan through the request types and see "Something else" at the bottom better.

**Comment by Nness** [comment]
We had `Something else` button been displayed differently at start. It was located at right side of request type list. After initial release, many customer find out most of user uses `Something else` rather than the request type they have designed.

There are several issues to this.
* The button is too prompt. It has least effort to discover it. (I doubt this is the main reason)
* Poorly designed request type. This happen in 99% of our customer base. Most of customers are not UI/UX designer. They often fallen into following trap.
    * MSP use request type as a tool to do their job. Rather than analyse the ticket and put it under proper type, sub type themselves, they create huge hierarchy of request types, and expect user to sort type and sub type for them.
    * MSP does not analyse user's behaviour. They do have data on which kind of ticket their customer often submit. But rather than design request type based on user's needs, they just throw most common scenarios there and expect customer to find it from the list.

The outcome is that some of our customer ask us to provide toggle to turn off something else. Where others ask us to make button more subtle. And only appear at end of the list.

## Proper request type design.
Rather than get into improvement of the button, I will try to go through what I believe is better request type design. 

1. Understand the user base. From the history data, analyse between different companies. For each company, then perform following.
    * Choose 3~5 most requested issue and see if any of them have greater impact if turn them into request type + form. (impact as decrease the time needed to solve the issue)
    * Explore rare request, see if there are issues that can be beneficial to create form. Such as new user on boarding. Such scenario can be benefit from form. 
2. Based on the research, only create small amount of request type + forms. During monthly or quarterly meeting, present to the customer.
3. After few month, perform similar research again, to see which one has been used and are there anything not been covered. Adjust if needed.

For such design, we encourage less is more. If we put ourselves at user's perspective, and I have an issue I want to resolve. When I look at 100 of request types, it is not fun. It creates more issue then the issue I have on my hand. Thus, if I see an escape route, I will choose it rather than search or find it. As at end of day, I paid the money to be served, doesn't matter which request type I use, you have to solve issue for me. That's the end user mentality. Unless there aren't many request type for fast scan, people will skip it.

Now, the cost of such analyse, research and design take time and effort. Which it should only apply to small group of customer you have. Which is high value customers. For others, generic request types will do. But not too many of course. 

## Make the button more prompt.
I have went through the history and the ideal solution of design request type. The reason is, have too many setting to alter the outcome is not ideal. More setting we have, then we need university and training before user can use our product. Modern software, simpler is better.

Rather than have more setting, I want to explore an solution that many can accept. Current thoughts on this is.

* `Something else` still at end of list.
* Same style, not too prompt.
* By default, different to other request type, it should have underline.
* When user search for request type and cannot find it. The empty state should provide something else.

**Comment by Nness** [comment]
- [x] Underline added for something else button.
- [x] When user unable to find request type during search, something else button appear as 'General Request' button under not found card.

Expect change to be live within 30 min.
