### ISSUE TITLE
[26688, 26742, 27041] Ticket event for when a Member is assigned to a ticket

### ISSUE THREAD

**Issue by iskolares** [DeskDirector/UserVoice#629]
Currently, there is no ticket event when a member is assigned to a ticket , which DD customers can use to wire automation to like sending a notification to a tech when they are assigned to a ticket.

With the current events, members only get notified if the ticket is updated they are assigned to.

**Comment by iskolares** [comment]
Related ticket #26742 - they want to send a notification to the tech once they are assigned to a ticket

**Comment by iskolares** [comment]
Related ticket #27041 

They are trying to setup a Team notification for team members when they are assigned a ticket.

**Comment by ahericks75** [comment]
We would like to use this to send Teams adaptive cards when someone is assigned to a ticket.  This is definitely a preferred method versus email.

**Comment by DDAndyChen** [comment]
The coming update release will address this issue.

What's new

* new workflow event: `ticket.assigned`: occurs when an agent/member is assigned to a ticket.
* Power Automate DD connector: for a ticket workflow flow, it can triggered by the new event and optionally filtered by an ID of the member that is being assigned.

Remarks:
* For the standalone DD, DD with ConnectWise integration and DD with Autotask integration, assigning member in DD Tech triggers the event;
* For DD with CW, merely assigning a member in CW Manage won't trigger the event unless the ticket is also updated after the assignment. This is because in CW, assign a member doesn't mark the ticket as updated and without the update event DD is not able to pick up the changes.
* For DD with AT, assigning primary resource in DD Tech/Autotask can trigger the event; Assigning secondary resources in DD Tech/Autotask will not trigger the event.
