### ISSUE TITLE
[37739] Email template recipients to use PSA model's first name if exist

### ISSUE THREAD

**Issue by prysmcorp** [DeskDirector/UserVoice#642]
We have run into a situation when using the email templates out of DD where the contact's first name is truncated. That's because there is a space in the user's first name. While 'FeaturedNote.User.Name' works okay and shows the entire name correctly, the 'Recipient.FirstName' token only displays a partial name.

Edcel recommend introducing a field. Could we have a Nickname field that is pulled from ConnectWise and then use an IF ELSE statement within the MJML code? It would then pull the nickname if populated or else pull the First Name.

**Comment by prysmcorp** [comment]
Reference to ticket number 37739.

**Comment by Nness** [comment]
- Gun put on the head solution: Load recipient data from database and populate first name from PSA data. Due to memory and network impact compare to the benefit, such approach will be the last effort. It take least amount of change but with sacrifice on infrastructure resource.
- Long term solution #1. Change in memory process of email delivery into database queue, that way we can limit amount of operation pending in the memory and allow us to perform complex business logic. So we could populate first name more accurate based on PSA data.
- Long term solution #2. Based on version 1, but introduce additional field that user can specify the name they want to be called. ConnectWise we could use Nickname, but it is not best representation of the actual data. e.g. my nick name is nness but that's now how I want to be called. 

We will evaluate existing implementation, if first one can be achieved without sacrifice on infrastructure resource consumption, then we could achieve it within days, else this will be pending until we changed approach of email delivery.

**Comment by Nness** [comment]
After evaluation, it is populate first name from PSA's first name without additional cost. It means server side small memory footprint increase, which we will take that. Adjustment should be released on next server release. Talk with our support on early adoption if it is urgent.
