### ISSUE TITLE
DD Tech: Change Contact

### ISSUE THREAD

**Issue by FluidNets-DamianS** [DeskDirector/UserVoice#67]
Change contact should display list of active contacts at current company.  Currently displays list of every single contact.

**Comment by Andrew-Lahikainen** [comment]
I think changing contact needs more design. The reason it behaves as it does currently is because we wanted to support the case where you need to change the company which implicitly happens as a result of changing the contact.

A really simple, hacky way of "fixing" this could be to include a flag on the change contact dialog that would restrict the search to the same company which would be enabled by default.

**Comment by FluidNets-DamianS** [comment]
I think an easy fix would be to have DD Tech follow the "Company Type Filter" from the Admin Console.
![image](https://user-images.githubusercontent.com/10325877/42396891-a7bb8232-8131-11e8-806a-f359524d6f73.png)

**Comment by Andrew-Lahikainen** [comment]
I don't think this would solve your original problem though would it? I thought you wanted to change contacts within the same company without seeing contacts from all other companies. This would still happen with this filter, just at a smaller scale.

**Comment by FluidNets-DamianS** [comment]
Within the same company is best... But it's hard to say.  The smaller scale is way better.  However in CW you can also make contacts from companyA appear as the contact on a ticket for companyB.  It just depends on how the enhancement is implemented.  The example above is extreme but I do it often enough.

**Comment by Andrew-Lahikainen** [comment]
@FluidNets-DamianS Tech has been updated to restrict results to the same company by default. This should make it a little easier to change contact.

If you would like to see the visibility filters implemented in Tech can you please open another issue?
