### ISSUE TITLE
[46474] v5 Favicon Detection Logic Update

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#686]
When installing the v5 desktop client, the favicon validation check looks in the working directory, not the directory where the msi file is located. This is causing customers to get unnecessarily creative to script the installation of the v5 client in our RMM (CW Automate). Using the standard method of installing an msi via CW Automate scripting doesn’t work because the built-in favicon check fails.

**Example without changing installation directory**
![image](https://user-images.githubusercontent.com/30588784/200446937-560a2413-7462-4140-a548-b7fd44cbe724.png)

**Example after changing installation directory**
![image](https://user-images.githubusercontent.com/30588784/200446952-2a862f40-1a15-43fd-b94d-610b7ece763b.png)

The RMM scripting engine allows us to install an MSI via a single command where we only have to pass the arguments ( /i “path-to-msi” /qn) - but this runs msiexec from its installed location under C:\Windows\System32 which results in the portal installer failing.

**Comment by Nness** [comment]
Due to difficulty to working with branding and MSI limitation, the solution for this is to store all files under `C:\Temp\DeskDirector` folder and use RMM to execute the MSI. That has been described from article below.

https://help.deskdirector.com/article/9nnevzf45s-deploying-dd-desktop-portal-v-5-via-power-shell
