### ISSUE TITLE
[48974] Filter out ConnectWise companies based on deletedFlag:True

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#704]
Scenario: Company merged in ConnectWise. The status of this company stays in an ACTIVE state:
```
"status": {  
    "id": 1,  
    "name": "Active",  
    } 
```
This displays the company within DD Admin Console.

Feature request to automatically exclude deleted customers based on the following flag:

```
deletedFlag : True
```

**Comment by Nness** [comment]
This is more like a bug in ConnectWise rather than a feature we can implement. The problem for ConnectWise merge is the company got deleted has the flag setup to `true`, but the `LastUpdated` property remain same. Where our system use `LastUpdated` property to detect change of the entity, with such behavioiur, we are unable to detect.

Even during resync, the data will remain same.

What we can do is during resync to have logic to discover such behaviour, but incremental sync we don't have any solution.

**Comment by Aycorn** [comment]
> 19.94.3 has change to detection. The outcome is that our system will re-synchronize once every three days, during that time, our system should be able to pick up deleted company.
