### ISSUE TITLE
Contact Sync with Active Directory

### ISSUE THREAD

**Issue by lct-burhank** [DeskDirector/UserVoice#705]
Would it be feasible to introduce a feature to sync contact in DDTech with Active Directory?

**Comment by Nness** [comment]
If you could contact support on this and put ticket ID on this issue's title will be appreciated. so we can associated this with actual customer.

**Comment by Aycorn** [comment]
Closing this issue - DeskDirector for ConnectWise and Autotask use the contacts within the PSA as the source of truth. The sync contact feature will need to be requested from your PSA provider instead of implemented as an out-of-the-box DeskDirector feature.

If this is not available through your PSA, you can explore building this as a bespoke automation and leveraging DeskDirector's [Power Automate](https://help.deskdirector.com/article/fx5qezmokf-power-automate-administration) suite as required.
