### ISSUE TITLE
#540290 - Bug fix - Members can access and use Tech Portal despite it being disabled for them in the admin portal

### ISSUE THREAD

**Issue by Leeroy-Steele** [DeskDirector/UserVoice#728]
Members with "Allow access TECH portal" - **Disabled** in the admin portal are still seeing it as a login option. Once they login to it they can still navigate all of the tabs except the tickets tab. They can also find and update tickets through a company or contact

**Comment by Nness** [comment]
I can reproduce this in the development environment, I can confirm this is unexpected behaviour. One thing to be clear, the original goal of the flag is not to stop TECH from access or modify tickets, it is avoid them accidentally enter TECH portal be billed. How we count activity in billing is whether user modified tickets.

The flag is there during we deploy the fix on member/resource use tech portal metered billing. We believe it served its purpose, to make TECH portal harder to use. 

To completely disallow someone from modify tickets, you can always reduce their access in company restriction or board restriction.

I will exam the code history to see why the behaviour like this. It might related to broad cast and few other feature. That we want member to use but won't be billed. The flag itself is a bit misleading.

**Comment by Nness** [comment]
From login perspective we never disallow login, we only block tickets from be viewed. Due to user can navigate to ticket detail from contact or company page, we have new TECH portal adjustment release to improve that.

The reason we want to allow member to login into TECH portal is  due to broadcast. Broadcast historically always available for all members.

Adjustment is on CI/CD
