### ISSUE TITLE
[10745] Ability to hide .eml attachments within DD Portal

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#78]
Any replies received via email within ConnectWise attaches a .eml file visible to the end users on DD Portal.

Request to have this hidden or disabled as an option.

![image](https://user-images.githubusercontent.com/30588784/42478450-dfe61150-8428-11e8-8c08-336eabda1f2e.png)

**Comment by Nness** [comment]
Ticket timeline is currently on redesign. One of goal is to remove noise from attachments. It will be similar to following design.

I will decline this issues for now until redesign is done. If customer still want to hide or disable those attachments, then we can review this request again.

This request declined is because it is targeting an interface is mean to be redesigned. In the future, similar request should be against new design to be able to accepted.

![2018-07-10_10h43_51](https://user-images.githubusercontent.com/1712143/42479689-250ea882-842e-11e8-8659-c702167b0333.png)

**Comment by Nness** [comment]
New design will be similar to Github, improve scan on ticket note instead of event or attachments.

**Comment by Aycorn** [comment]
Similar request raised: Service Ticket #13059 - DD and ConnectWise Closed Loop

**Comment by bur4an** [comment]
Similar request raised - Service Ticket #14043 - Bug - DD V18

**Comment by NetFusionDesigns** [comment]
The new interface is out, and this issue still persists - we constantly get customers asking us to hide the .eml as it confuses them. Please fix

**Comment by Nness** [comment]
The new interface has not yet finished.
