### ISSUE TITLE
[10640] Sticky Broadcast Notifications for DDPortal

### ISSUE THREAD

**Issue by Nness** [DeskDirector/UserVoice#86]
Similar to legacy WPF portal, we want notification of broadcast to be able to sticky on customer's screen until they are acknowledged.

**Comment by chris-ls** [comment]
Windows/macOS do not currently support "Sticky Notifications" i.e. notifications that stay on a users screen until they are dismissed.

Implementing this feature for the Portal will require the development of our own notifier UI, managed by the application itself rather than the OS.

If this feature is turned ON for a given desktop client, we will cease to use the OS notification system all together (for broadcasts, ticket updates etc.) so that the end user isn't receiving 2 types of notifications from the Portal.

This feature will be implemented by effectively running a second application window on the users machine.
This will incur an additional overhead of about 30mb.
There will be a new registry setting introduced, which will be able to turn OFF this system on a per machine basis, primarily so it can be turned off for Citrix/TerminalServer type environments, where 30mb extra memory consumption per user may be too much.

When this system is turned ON, only "Important" broadcasts will become sticky.
"Info" type broadcasts and ticket update notifications will not be sticky.

Each notification will have a "Dismiss" and "View" action.

**Comment by chris-ls** [comment]
Estimated delivery date for this feature is end of September.
This includes development, testing, configuration, initial feedback.

Please contribute any ideas/suggestions/concerns about this feature :)

**Comment by chris-ls** [comment]
Currently we are thinking of only providing this as a GLOBAL setting.
i.e. If you turn this on, every user and every company will now see the new notification UI, if they are using the Desktop Portal.

**Comment by chrisalexssa** [comment]
We would also like the ability to "Sticky Notify" an individual user. This will save us lots of time trying to reach certain users that don't respond to email or tickets.
Thanks,

**Comment by chris-ls** [comment]
@chrisalexssa 
Is that a common issue you guys face? 
It seems strange that users wouldn't reply to email/tickets from one of their service providers.

I can see how a general "Sticky Notification" could solve this problem, but it would be good to try and understand these users more, as there might be other issues/solutions present.

Do you know _why_ they don't respond to email/tickets?
Is it because they just don't realize they need to get back to you? i.e. an issue with the current email/ticket notification systems.

Also, how would you imagine sending one of these per-user sticky notifications?
In the context of a ticket? Or just simply "Send this message to this user".

**Comment by chrisalexssa** [comment]
One example is when the user doesn't have email (or ignores their email notifications). Their only path to see a ticket not is to login to DD however they are all busy so we can't rely on them to do that. They do not realize that they need to get back to us. Here is another more frequent example: Yesterday we met with a client where we are rolling out MFA (Multi-Factor Authentication) for 200 users. We need to communicate with them to tell them that on Wednesday MFA will be enforced and that they will need to follow a link to the instructions, etc.... Many users are part-time workers and part-time computer users. They did not make a ticket so they aren't thinking about checking a ticket. Of the 200 users, we are only doing 10 on Wednesday so it would be helpful to not notify all 200 users for this. Email is a possibility but is often ignored.
Does this help?

**Comment by bobsquid** [comment]
We experience the same type of issue fairly regularly, so I definitely agree with @chrisalexssa on this.  A sticky that can be assigned to an individual user (or to a single company) would be fantastic.  A single company sticky would be handy for notifying users of a pending cutover, service interruption or other pertinent info that wouldn't be relevant on a global scale.

**Comment by chrisalexssa** [comment]
Has there been any progress on this project?

**Comment by chrisalexssa** [comment]
Hello,
The completion estimate was September. Has there been any progress?
Thank you,

**Comment by chris-ls** [comment]
@chrisalexssa Work has resumed on this feature.

The scope for the first release will be:
* Display only Important Broadcast notifications using the custom notification system. Other notifications will continue to use the native OS system.
* Provide a way to turn on/off Sticky Notifications from your Admin Console
* Provide a way to disable Sticky Notifications for an individual workstation via. a registry key

I will also update the proposed designs & UI behavior of the sticky notifications, once those have been finalized. Feedback would be appreciated on this part.

**Comment by chris-ls** [comment]
Just a quick status update.

There was technical debt that needed to be addressed in the current desktop application before this feature could be easily added.
This work is now almost complete, the actual sticky-notification feature should follow easily after this.
Delivery of the initial version should be expected this month.

**Comment by chris-ls** [comment]
Final testing is taking place.

Documentation explaining the feature, it's scope and how to turn it on/off needs to be written.

Will be released Mid March

**Comment by chris-ls** [comment]
@chrisalexssa @bobsquid  Thanks for your patience on this one.
The initial version has been released in v2.2 of the Windows client.
You can find that available to download inside your Admin Console.
Any MSI deploys you have should have already updated by themselves.

You can find documentation on this feature here:
https://help.deskdirector.com/article/mgf2r3p3w6-sticky-broadcasts

The documentation explains how to turn the feature on/off.
Initially I recommend using the 3rd approach in the docs, where you will use a registry key to turn the feature on for specific machines. (to test it out)

The checkbox in the Admin Console to enable the feature globally isn't there just yet, but will be arriving in the next week or 2.

This feature is still very much open to change & improvement, so any feedback is appreciated.

The current behavior of the Sticky Broadcast is to show a generic message and require the user to view the full notification inside the Portal itself.

**Comment by Andrew-Lahikainen** [comment]
This was released a long time ago. Closing.
