### ISSUE TITLE
[10838] Embedded satisfaction surveys

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#91]
Ability to have a customer survey solution integrated or embedded into closed ticket interface.

Rough concept:

![image](https://user-images.githubusercontent.com/30588784/42971072-2bda1308-8bff-11e8-9a65-4c13f01009d5.png)

**Comment by Nness** [comment]
We implement it and removed it. The part that didn't functional well is people don't know they can provide feedback inside portal. A email approach is much better than inside portal. 

We can provide smile back consulting work for anyone who needs it. We might look at this again in the future.

**Comment by Nness** [comment]
[SmileBack](https://www.smileback.io/)

This can be integrate with Autotask and ConnectWise through workflow, trigger by ticket closed.

**Comment by bobsquid** [comment]
We've used CrewHu to send email surveys for a few years now, so it's already set up with workflows.  


The problem is I'm finding that some users have stopped paying attention to the closure email, as they just use the DD portal to read the closure notes instead.  If we can add the survey to the closure notes in DD it would help regain those lost surveys.  


The point of the DD portal is to be a single pane of glass for users, so it's more inefficient to make them check multiple places.

**Comment by Nness** [comment]
@bobsquid . How do they read closure notes inside portal? Through email notification? Since if they go to portal and the ticket already closed, default panel only showing open tickets. They have to specifically go to closed ticket panel to see it.

If we ever implement satisfaction survey, what will you expecting? Do you expecting us to send to CrewHu? Or in other word, where do you expect to analyze feedback data.

**Comment by FluidNets-DamianS** [comment]
This is a great idea.  However you should be able to implement today.  As long as you insert the HTML content into the last update of the ticket and it is formatted correctly it should display properly.

**Comment by FluidNets-DamianS** [comment]
In addition it could also be sent in an email resulting in the user seeing it in the portal and in email format.  I did not take the time to clean up the HTML for my test, but the needed HTML is rendered correctly in email, DDportal and DDtech.  CW will show raw HTML.

**Email**
![image](https://user-images.githubusercontent.com/10325877/43000391-3f5f9854-8bef-11e8-8d6a-c21975636a23.png)

**DD Portal**
![image](https://user-images.githubusercontent.com/10325877/43000417-52c0866a-8bef-11e8-964f-3bb3e9280b15.png)

**Comment by bobsquid** [comment]
Thanks for the suggestion Damian, I'll give that a shot!

**Comment by FluidNets-DamianS** [comment]
Also, i see (2) ways to automate it - Manage Workflow that Triggers an Automate update to the ticket or Zapier.

**Comment by Aycorn** [comment]
If this was offered as an addon within Desk Director - a way to show closed tickets that have/haven't received feedback would be a good way to increase feedback statistics:

![image](https://user-images.githubusercontent.com/30588784/44245914-7ed74580-a22f-11e8-9aad-50ad54d290aa.png)

Something like this where clients can filter closed tickets that haven't received feedback. And when they have give an easy interface that allows for Positive, Neutral, Negative or Ignore. This would then transition to an "Additional Comments" section if not ignored. Would just need a super clean UX/UI design to make this process as easy as possible but still retain relevant feedback information.

![image](https://user-images.githubusercontent.com/30588784/44245975-d8d80b00-a22f-11e8-94d1-7a9f1a1e8c1c.png)

![image](https://user-images.githubusercontent.com/30588784/44246003-fad18d80-a22f-11e8-9511-42966386b4b7.png)

Something similar to what Global Trading companies (Aliexpress/Ebay) provide.

You could also have how many reviews the user has left under their profile too? However this might prompt end users to log more tickets than required - food for thought.

**Comment by Nness** [comment]
This is done. we have our own survey system now.
