### ISSUE TITLE
[10875] Ability to CC when submitting tickets.

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#92]
Ability to have a CC option when submitting a DD form.

Potentially as a dedicated form addition/section in case Techs don't want this enabled for every form.

![image](https://user-images.githubusercontent.com/30588784/42974308-c6dd119c-8c0a-11e8-9f2c-572425a5ddb3.png)

![image](https://user-images.githubusercontent.com/30588784/42974369-0bca323a-8c0b-11e8-936a-658fa9160f36.png)

**Comment by Nness** [comment]
This will never been accept through DD-Form. DD-Form stands for collect data. This logic can be implement outside of form. Same as attach file when submit ticket. Should attach file be part of form? No. That's part of submit ticket process.

@Aycorn  you can create user voice for CC options as separate issue without mention DD Form. Since this doesn't fit with DD-Form.

**Comment by Aycorn** [comment]
Thanks @Nness - I have logged this through as a separate request:

https://github.com/DeskDirector/UserVoice/issues/93
